### ISSUE TITLE
Combat Effects for Combat Extended

### ISSUE THREAD

**Issue by Axlkss** [AthenaSulisMinerva/CombatExtendedFastTrack#100]
CE Parch:https://steamcommunity.com/sharedfiles/filedetails/?id=1756442393&searchtext=Combat+extendet+

**Comment by sumghai** [comment]
This does look amazing, but I think visual enhancements like these should be an optional rather than standard feature (and no, we can't simply include these and add a "toggle" to turn it on/off).

@AthenaSulisMinerva?

**Comment by AthenaSulisMinerva** [comment]
I actually run this mod myself, and really like the effects.

However, @sumghai is right in saying that this shouldn't be a core part of CE:FT, so we're not going to integrate this.
