### ISSUE TITLE
Combat Extended Patches

### ISSUE THREAD

**Issue by Axlkss** [AthenaSulisMinerva/CombatExtendedFastTrack#101]
Simplified CE Ammo:https://steamcommunity.com/sharedfiles/filedetails/?id=1721900229
Optimization: CE Ammo:https://steamcommunity.com/sharedfiles/filedetails/?id=1721900020
Generic CE Ammo:https://steamcommunity.com/sharedfiles/filedetails/?id=1722042312

**Comment by sumghai** [comment]
As per #94, the CE:FT team has decided that these "optimizations" go against the spirit of CE:FT providing integrated support for a wider range of mods, and so we will never integrate these patches.

**Comment by Axlkss** [comment]
I do not understand about * the spirit * of the CE: FT, since there are people who prefer to play this mod with optimization mods, at least the mod to optimize the ammunition, it is a headache the ammunition of each weapon...

**Comment by HappyHead** [comment]
You may be better off convincing the author of this mod to work in a version which simplifies all ammo types addressed by CE:FT
https://steamcommunity.com/sharedfiles/filedetails/?id=1892397131&searchtext=ammunition

The way CE works, weapon damage is calculated based on the ammunition used, not the gun doing the firing. To make things compatible with mods which make new weapons, new ammos need to be made which approximate the weapon's intended damage value.

If, however, having weapons only distinguished by "class" is ok with you, an ammo replacement mod which has 1 type of ammo for each "type" of weapon could offer the simplicity you're looking for.
