### ISSUE TITLE
Shotgun ranges

### ISSUE THREAD

**Issue by Sevrun** [AthenaSulisMinerva/CombatExtendedFastTrack#104]
Don't know if this is the right venue, but I'll jump straight in, they're ridiculously short.  Pistols are generally accepted to reach to about 20-30 meters.  Even short barreled tactical shotguns have a range of roughly 35-50 meters and retain moderate effectiveness.  Hunting shotguns?  70+ meters.

Shotguns being handed the same ranges as a pistol (12) makes a weapon of already limited use fairly irrelevant.  I grumbled under straight CE where their ranges were at least 16, but 12 is just too short in my admittedly meaningless opinion.

I don't put this out there with the intent of being a jerk, or trolling.  Just trying to be clear in my meaning.

**Comment by AthenaSulisMinerva** [comment]
Unfortunately, this issue is something you'll have to raise with the original Combat Extended mod team, as they established the standardized calculation spreadsheets that CE:FT uses when patching and balancing weapons.

CE:FT adds extra ammo definitions and support for more mods, but otherwise tries not to stray too far from the original CE's gameplay mechanics and balance.

**Comment by Sevrun** [comment]
I'll go rattle their cages then, but actually digging through the defs to your Rimunation patch has shotgun ranges...  well, shotgunned from 11 all the way to 20.  Snagged a copy to adjust for personal use, no biggie.  Haven't dug though the other patches to 3rd party content yet.

Is there any place I could get a look at these spreadsheets?

**Comment by AthenaSulisMinerva** [comment]
https://github.com/NoImageAvailable/CombatExtended/wiki/Stat-&-Balance-sheets

CE:FT has its own private copy, which uses the exact same formulas. We'll make our version of the spreadsheet publicly available once CE:FT has fully transitioned over to CE 1.6's revamped projectile and armor system.
