### ISSUE TITLE
Arachne Race CE patch

### ISSUE THREAD

**Issue by Magichp** [AthenaSulisMinerva/CombatExtendedFastTrack#105]
Base mod : 

https://steamcommunity.com/sharedfiles/filedetails/?id=1589454687

CE patch:

https://steamcommunity.com/sharedfiles/filedetails/?id=1901128577

As I mentionned in the workshop description, this is my first CE patch, please do point any issues so I can try to solve it ;)

**Comment by AthenaSulisMinerva** [comment]
When we get around to adding this, we'll help reformat and rebalance the patches for you if necessary.

**Comment by Magichp** [comment]
Thanks, I'm waiting for some feedback from users and the update to the main Combat Extended branch, I'll update accordingly and make a first balance pass then. After that, I'll probably leave it to you ;)

**Comment by Magichp** [comment]
Updated to CE 1.6 and rebalanced a bit.
The patch for 1.5 that is working with the current FastTrack is still available if anyone need it.

https://steamcommunity.com/sharedfiles/filedetails/?id=1904384309

**Comment by sumghai** [comment]
@AthenaSulisMinerva - This went through over on the upstream CE repo, so I've merged it into ours as well.

You still want to check it yourself before closing this issue, right?

**Comment by sumghai** [comment]
Closing as this has been included in FT-006.
