### ISSUE TITLE
Sidearms and out of ammo issue

### ISSUE THREAD

**Issue by shivachirr** [AthenaSulisMinerva/CombatExtendedFastTrack#106]
1. im wondering if this is compatible with sidearms or dose the same issues from the original combat extend still persist or that is has been fixed and never noticed

2. ive noticed in a prolonged gun fight when my colonist or well droids run out of ammo the move the gun to there inventory, and when they grab ammo they never pull it back out into their equipped slot. this is despotically annoying when i have some colonies just watching the fence killing off zombies and they run out of ammo put their gun in there backpack and never pull it back out when needed when they pick up more ammo

**Comment by AthenaSulisMinerva** [comment]
> im wondering if this is compatible with sidearms or dose the same issues from the original combat extend still persist or that is has been fixed and never noticed
You should ask this question to the original Combat Extended mod team. CE:FT simply forks the existing CE codebase by adding more compatibility patches, not making fundamental codebase changes or bugfixes.

> ive noticed in a prolonged gun fight when my colonist or well droids run out of ammo the move the gun to there inventory, and when they grab ammo they never pull it back out into their equipped slot. this is despotically annoying when i have some colonies just watching the fence killing off zombies and they run out of ammo put their gun in there backpack and never pull it back out when needed when they pick up more ammo
Again, this is standard CE behaviour, which you will need to ask the original CE team about.

In the future, please only post one question per issue, as multiple questions per issue makes it harder to divide up work among our (small) team.
