### ISSUE TITLE
Expanded Rims mod

### ISSUE THREAD

**Issue by oscar370** [AthenaSulisMinerva/CombatExtendedFastTrack#107]
The nanotech weapons and the weapons used by the watchers do not work, they just keep pointing, but they never fire and only generate many errors in the console.

**Comment by sumghai** [comment]
Glitter Tech does not have any "nanotech" weapons, nor does it have a faction or pawntype called "watchers".

Perhaps you have confused Glitter Tech with a different mod?

**Comment by oscar370** [comment]
Oh, it's true, I'm sorry, I was wrong. Although I could make a patch for Expand Rims which is the mod with which there is an incompatibility or if there is already a patch, you could inform me.

**Comment by sumghai** [comment]
Right, so it's the Expanded Rims mod.

I took a quick look at it, and my main concern is that ER's "modulable" weapons system might not be easy to patch for CE, especially as its weapon-switching behaviour is probably incompatible with the ammo/firemode model that CE uses.

We might look into this someday, but I'm afraid this will likely be _extremely_ low on our current list of priorities.

**Comment by oscar370** [comment]
No problem. Thanks for answering!
