### ISSUE TITLE
Ammo Disappeared

### ISSUE THREAD

**Issue by PentalimbedPuss** [AthenaSulisMinerva/CombatExtendedFastTrack#112]
All ammo disappeared excepted mechanoid ammos and 5.56x45 variations. Toggling ammo options in config shows in GUI:

Exception from long event: System.NullReferenceException: Object reference not set to an instance of an object
  at CombatExtended.AmmoInjector.InjectAmmos () [0x00000] in <filename unknown>:0 
  at CombatExtended.AmmoInjector.Inject () [0x00000] in <filename unknown>:0 
  at Verse.LongEventHandler.UpdateCurrentSynchronousEvent (System.Boolean& sceneChanged) [0x00000] in <filename unknown>:0 

which also logs when loading the game. With only core and CE:FT there's no problem, but I have such a long modlist that looking over each one of them is nearly impossible.

FYI, standalone patches and mods that I've installed are:
Sparkling worlds
Sangvis Ferri Weapons Pack CE
Dragonian Race Weapons Permit patch
Androids
RPG Inventory

They and CE:FT are placed at the bottom of the modlist

Mods that are patched with FT edition are:
A Rimworld of magic
Animal Collab Project
Apparello 2
Gas Trap and Shell
Kurin
More Vanilla Turrets
NewRatkinPlus
Rabbie
RBSE
[RH] Faction: Last Man Mercs
[RH] Faction: Militaires Sans Frontieres
[RH] Faction: Umbra Company
Red Horse Furniture

Other error that might or might not related:

XML error: Could not find parent node named "81mmMortarShellBaseCraftableBase" for node "ThingDef".
XML error: Could not find parent node named "Base81mmMortarShell" for node "ThingDef". 

Config error in Shell_GasFear: has null thingClass.
Config error in Shell_GasFear: has components but it's thingClass is not a ThingWithComps
Config error in Shell_GasFear: CompExplosive requires Normal ticker type
Config error in Shell_GasAcid: has null thingClass.
(The same for all Gas Trap and Shell modded shells, thus they don't appear in the game)

**Comment by sumghai** [comment]
>With only core and CE:FT there's no problem, but I have such a long modlist that looking over each one of them is nearly impossible.

Unfortunately, since you've indicated that CE:FT on its own has no issues, a binary search is the only way you'll find out which mod is conflicting with CE:FT.

Could you please get back to us once you've identified which mod is causing the issue?

**Comment by sumghai** [comment]
Closing due to lack of response.
