### ISSUE TITLE
[Pratt] WWII Weapons Pack 

### ISSUE THREAD

**Issue by Hellfire42** [AthenaSulisMinerva/CombatExtendedFastTrack#114]
https://steamcommunity.com/sharedfiles/filedetails/?id=1894552878

**Comment by sumghai** [comment]
It looks like the author (Pratt) is releasing standalone CE versions of his weapons packs.

Nonetheless, I'll still do the CE:FT integrated patches.

**Comment by skycrossercat** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1920278294&searchtext=pratt
Pratt just uploads one of his WWII weapon pack's CE version,  it may have some tweaks on his consideration.  If CE:FT has patches for these weapons, is it needed to use vanilla version only to prevent some duplication?

**Comment by sumghai** [comment]
Yes, the CE:FT patches are intended to be used only with the vanilla versions of Pratt's weapons mods.

ASIDE: One criticism I have regarding standalone CE or CE:FT-only versions of mods is that it adds unnecessary workload for the original mod author, as they would have to now essentially maintain two different versions of the same mod, and newbie users tend to get confused as to which version to get.

A standalone CE patch pack is marginally better, except that newbie users often either to forget to also install these patches, or are confused about the correct load order.

Bundling CE patches within the original mod itself is perhaps the most ideal option - while the mod author still has to do some work, at least this means everything is in one place, and users won't have to worry about load orders or dependencies. One disadvantage, though, is that non-standard ammo isn't shared with other mods, so you might have a situation where two different mods implement separate, incompatible versions of essentially the same ammo.

For mods whose authors are unfamiliar with or unwilling to include CE support, that's where CE:FT steps in and provide built-in patches, with the added advantage that any new ammo gets included in our central library and can thus be shared with other gun mods.

**Comment by sumghai** [comment]
Okay, first big half of the patches are done - I've tested each and every ranged, melee and turret weapon, and confirm that they all work.

The only thing left to do are to patch the three grenades, which will be quite a challenge.

**Comment by sumghai** [comment]
Grenades are now patched and working.

I have also replaced Pratt's original automatically-generated crafting recipes with CE-standardized ones, which allows pawns to craft 10 grenades of each type just like stock CE grenades, using CE-balanced costlists.

So yeah, this is pretty much done.
