### ISSUE TITLE
Rocket Launcher Not Successfully Constructing

### ISSUE THREAD

**Issue by Obzedat** [AthenaSulisMinerva/CombatExtendedFastTrack#120]
The basic Rocket Launcher from the machining bench is not creating an unfinished project upon starting. The pawn will gather all the materials and deliver them to the table and a yellow bar will appear, but the materials remain on the table and when the job is complete nothing is created and the pawn hauls the materials back to their storage locations before starting it all over again. The triple rocket launcher seems to work fine, and I haven't tested the doomsday launcher.

I have the mod that disables mod authors if that is of any help.

**Comment by sumghai** [comment]
Does this happen only in CE:FT, or do you also experience this issue in the newest update to the original CE mod?

**Comment by sumghai** [comment]
Closing as user never got back to us with troubleshooting results.
