### ISSUE TITLE
CE 1.6 and issues with mods that edit faces

### ISSUE THREAD

**Issue by Theblessedwant** [AthenaSulisMinerva/CombatExtendedFastTrack#128]
So after further digging, and as much as the CE Teams claim of increases compatibility with the new armor and layer system. I can safely say that any mod that edits the looks, of the face such as the Show hair past helmet mod, and the facial animations mod, no longer work with CE. Since CE uses a completely new pawn face class in their code according to a modder, this is just creating huge headaches for other modders.

**Comment by sumghai** [comment]
Yeah, this isn't really ideal. However, where possible, CE:FT will avoid deviating from CE in terms of fundamental gameplay mechanics and systems, so I'm afraid there's not much I can do about this. :/
