### ISSUE TITLE
Mechanoids Extraordinaire updated

### ISSUE THREAD

**Issue by Magichp** [AthenaSulisMinerva/CombatExtendedFastTrack#135]
Corrected cross-refenrencing issues, updated stats for CE 1.6

http://www.mediafire.com/folder/j9lkwbgbtz9ao/MechanoidsExtraordinaire

**Comment by sumghai** [comment]
Thanks! I'll manually merge this in tonight.

**Comment by sumghai** [comment]
For future reference, @Magichp, please put the files in a ZIP file next time, so that I can download them in one go - right now, you have them in Mediafire folders, and I had to download each file individually because only Premium accounts can download multiple files and folders.

**Comment by sumghai** [comment]
This is now good to go.
