### ISSUE TITLE
Rimefeller Heat Protection of Synthamide

### ISSUE THREAD

**Issue by Theblessedwant** [AthenaSulisMinerva/CombatExtendedFastTrack#137]
So i checked the heat protection of synthamide from Rimefeller and noticed there was no heat protection indicated on it within the patch. The sharp and blunt protections are fine, however the lack of heat protection being indicated in the patch results in the original heat protection being used which is set at 288% which when applied to parkas and jackets that have  a x10 material multiplier for heat protection of said material, it results in ridiculous levels of heat protection of over 2888%. A quick fix is to add 

	<li Class="PatchOperationReplace">
		<xpath>Defs/ThingDef[defName="Synthamide"]/statBases/StuffPower_Armor_Heat</xpath>
		<value>
			<StuffPower_Armor_Heat>0.052</StuffPower_Armor_Heat>
		</value>
	</li>
Into the rimefeller synthamide patch. 
![e162de30a48c5364aacb321494866482](https://user-images.githubusercontent.com/57470753/68733023-627faf80-0610-11ea-9b33-1cd3d51b0033.png)

**Comment by sumghai** [comment]
Thanks for the heads-up - I've updated the patch accordingly :)
