### ISSUE TITLE
Glittertech weapons dont have penetration

### ISSUE THREAD

**Issue by EldarFarseer** [AthenaSulisMinerva/CombatExtendedFastTrack#140]
i use your mod with the glittertech mod but some of the weapons like MRG5 rifle has no amorpenetration their single ammunation

**Comment by sumghai** [comment]
This is because the original CE team updated the upstream CE mod to use a different armor penetration system, which means all ammo and projectiles need to be updated as well.

See #69 for the ongoing discussion as to rebalancing the projectiles.
