### ISSUE TITLE
Glitter Tech mod - armor stat rebalance

### ISSUE THREAD

**Issue by TheDerpyPotato** [AthenaSulisMinerva/CombatExtendedFastTrack#145]
Looks to be broken, was working at some point
![rimtemp](https://user-images.githubusercontent.com/57368075/68904708-888a7a00-070c-11ea-8217-84acd2ff331b.png)

**Comment by sumghai** [comment]
Could you please be more specific as to what is "broken"?

The recent update to the 1.6/1.7 codebase from the upstream CE mod changed the way armor and projectile penetration works, and so most mod patches will need to be updated at some point or another.

The only thing I can see from your screenshot is that the GlitterTech armor value needs to be tweaked, as CE now uses actual Rolled Homogeneous Armor (RHA) and Megapascals (MPa) to define sharp and blunt armor protection respectively. The current values were based on the old scale-relative-to-100% model.

**Comment by TheDerpyPotato** [comment]
Well ya the armor values are so low, lower than they used to be. Looking at it there is the patch files currently in place but the values are too low like i said.

**Comment by TheDerpyPotato** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<Patch>
	<Operation Class="PatchOperationFindMod">
		<mods>
			<li>Glitter Tech</li>
			<li>Glitter Tech (No Surgery)</li>
		</mods>
		<match Class="PatchOperationSequence">
			<operations>

				

				<li Class="PatchOperationAdd">
					<xpath>Defs/ThingDef[defName="Apparel_NanoSuit"]/statBases</xpath>
					<value>
						<Bulk>100</Bulk>
						<WornBulk>15</WornBulk>
					</value>
				</li>

				<li Class="PatchOperationAdd">
					<xpath>Defs/ThingDef[defName="Apparel_NanoSuit"]/equippedStatOffsets</xpath>
					<value>
						<CarryBulk>15</CarryBulk>
						<CarryWeight>50</CarryWeight>
					</value>
				</li>

				<li Class="PatchOperationReplace">
					<xpath>Defs/ThingDef[defName="Apparel_NanoSuit"]/statBases/ArmorRating_Blunt</xpath>
					<value>
						<ArmorRating_Blunt>0.75</ArmorRating_Blunt>
					</value>
				</li>

				<li Class="PatchOperationReplace">
					<xpath>Defs/ThingDef[defName="Apparel_NanoSuit"]/statBases/ArmorRating_Sharp</xpath>
					<value>
						<ArmorRating_Sharp>1.25</ArmorRating_Sharp>
					</value>
				</li>

				<li Class="PatchOperationAdd">
					<xpath>Defs/ThingDef[defName="Apparel_NanoSuit"]/statBases</xpath>
					<value>
						<ArmorRating_Electric>0.8</ArmorRating_Electric>
					</value>
				</li>

				

				<li Class="PatchOperationAdd">
					<xpath>Defs/ThingDef[defName="Apparel_NanoSuitHelmet"]/statBases</xpath>
					<value>
						<Bulk>6</Bulk>
						<WornBulk>1.5</WornBulk>
					</value>
				</li>

				<li Class="PatchOperationReplace">
					<xpath>Defs/ThingDef[defName="Apparel_NanoSuitHelmet"]/statBases/ArmorRating_Blunt</xpath>
					<value>
						<ArmorRating_Blunt>0.75</ArmorRating_Blunt>
					</value>
				</li>

				<li Class="PatchOperationReplace">
					<xpath>Defs/ThingDef[defName="Apparel_NanoSuitHelmet"]/statBases/ArmorRating_Sharp</xpath>
					<value>
						<ArmorRating_Sharp>1.25</ArmorRating_Sharp>
					</value>
				</li>

				<li Class="PatchOperationAdd">
					<xpath>Defs/ThingDef[defName="Apparel_NanoSuitHelmet"]/statBases</xpath>
					<value>
						<ArmorRating_Electric>0.8</ArmorRating_Electric>
					</value>
				</li>

				

				<li Class="PatchOperationAdd">
					<xpath>Defs/ThingDef[defName="Apparel_Reactive"]/statBases</xpath>
					<value>
						<Bulk>20</Bulk>
						<WornBulk>15</WornBulk>
					</value>
				</li>

				<li Class="PatchOperationReplace">
					<xpath>Defs/ThingDef[defName="Apparel_Reactive"]/statBases/ArmorRating_Blunt</xpath>
					<value>
						<ArmorRating_Blunt>0.5</ArmorRating_Blunt>
					</value>
				</li>

				<li Class="PatchOperationReplace">
					<xpath>Defs/ThingDef[defName="Apparel_Reactive"]/statBases/ArmorRating_Sharp</xpath>
					<value>
						<ArmorRating_Sharp>1.4</ArmorRating_Sharp>
					</value>
				</li>

				

				<li Class="PatchOperationReplace">
					<xpath>Defs/ThingDef[defName="Apparel_NanoSkin"]/statBases/ArmorRating_Blunt</xpath>
					<value>
						<ArmorRating_Blunt>0.3</ArmorRating_Blunt>
					</value>
				</li>

				<li Class="PatchOperationReplace">
					<xpath>Defs/ThingDef[defName="Apparel_NanoSkin"]/statBases/ArmorRating_Sharp</xpath>
					<value>
						<ArmorRating_Sharp>0.9</ArmorRating_Sharp>
					</value>
				</li>

				

				<li Class="PatchOperationReplace">
					<xpath>Defs/ThingDef[defName="Apparel_NanoSpeed"]/statBases/ArmorRating_Blunt</xpath>
					<value>
						<ArmorRating_Blunt>0.15</ArmorRating_Blunt>
					</value>
				</li>

				<li Class="PatchOperationReplace">
					<xpath>Defs/ThingDef[defName="Apparel_NanoSpeed"]/statBases/ArmorRating_Sharp</xpath>
					<value>
						<ArmorRating_Sharp>0.3</ArmorRating_Sharp>
					</value>
				</li>

			</operations>
		</match>
	</Operation>
</Patch>

**Comment by sumghai** [comment]
I'll look into this when I have time.

**Comment by TheDerpyPotato** [comment]
Thanks, i remember when i got fast track a few days ago but then after i restarted the game the patch broke.

**Comment by sumghai** [comment]
> Thanks, i remember when i got fast track a few days ago it worked

That was because the FastTrack version you first downloaded was based on CE 1.5, which uses the old armor values...

> but then after i restarted the game the patch broke.

...and while you were restarting your game, Steam updated your copy of FastTrack automatically to the latest version based on CE 1.6/1.7, which of course would not 0lay nice with the original armor patch

**Comment by TheDerpyPotato** [comment]
Oh so CE:FT only recently got updated to 1.6. That would explain it. The whole deal with 2 different teams kinda just causes confusion and problems. Why doesn't everyone just work on one branch since CE:FT is just CE but with more patches but the mainline comes out slower?

**Comment by AthenaSulisMinerva** [comment]
We established CE:FT as a response to what we felt (at the time) to be slower update cycles in CE and their reluctance to accept patch submissions. There were also some nasty political issues involving specific mod patches being rejected for non-technical reasons as well, but we'd rather not dwell on that too much.

The most recent CE updates have demonstrated that the upstream team has acknowledged some of the issues behind their old release procedures; while the CE:FT team is happy to share data to ensure the core functionality of both mods share some level of parity, we are currently not considering a formal merger with CE at this time.

**Comment by sumghai** [comment]
Okay, I've updated the stats for both the nanosuits and the standard Orion Corp armor. These will get folded into our next FastTrack release.
