### ISSUE TITLE
Rimmu-Nation Corrected Layers for backpacks

### ISSUE THREAD

**Issue by Theblessedwant** [AthenaSulisMinerva/CombatExtendedFastTrack#147]
So i'm not sure if this is a bug but the backpack part of the rimmunation  layers hasnt been corrected yet, it still lists the layer as torso when it should correctly be shoulds and under the backpack layers so it can be worn with a webbing.

**Comment by Theblessedwant** [comment]
<value>
					<apparel>
						<bodyPartGroups>
							<li>Shoulders</li>
						</bodyPartGroups>
						      <layers>
        <li>Backpack</li>
			</layers>
	  </apparel>
					</value>

**Comment by Theblessedwant** [comment]
this should be there instead of the torso layer

**Comment by Theblessedwant** [comment]
![023e1c53f40dc45d67770424b1f20455](https://user-images.githubusercontent.com/57470753/68987410-c4d0ee00-0864-11ea-8bf4-d8f8195d71ed.png)

**Comment by sumghai** [comment]
Yes, these need to be fixed. I'll add this to our to-do list.

**Comment by Theblessedwant** [comment]
I think the vests  need  to be corrected too*

**Comment by Theblessedwant** [comment]
![8572fb832d985f54ad1113ecff295b1d](https://user-images.githubusercontent.com/57470753/69006140-11e8b900-0966-11ea-8aaa-f517fef4f5ae.png)
Here are the  vest layers,  it was a typo on my end for the other issue

**Comment by sumghai** [comment]
@Theblessedwant, @AthenaSulisMinerva sent you an invite to have contributor access. Would you be able to make the edits?

**Comment by Theblessedwant** [comment]
Disregard  the body part groups, they causes the vest and backpacks to  not show up,.

**Comment by Theblessedwant** [comment]
Update: So by replacing the apparel layer, you need to redfine the worngraphicpath for each individual new layer like so. 
I think you can alternatively just target the specific layers and bodypartgroups using patchoperationreplace , but this was how i handled it  The more efficient method would likely group them up and patchoperationreplace the layers and bodypartsgroup 
![da4d1bb87bb4c96e61ceb9afdbfa6904](https://user-images.githubusercontent.com/57470753/69007783-52076600-097d-11ea-900f-fe0952893bbe.png)

**Comment by Theblessedwant** [comment]
![23e9622d3f239746643bd82a7f2c30c8](https://user-images.githubusercontent.com/57470753/69007842-554f2180-097e-11ea-8807-e0977623acbf.png)
or this will work too

**Comment by sumghai** [comment]
Righto, I'll have a crack at this tomorrow night.

Usually, I lean towards patches that are grouped together for efficiency, but the reason we patch items individually for Rimmu-Nation apparel and weapons is because of the way RN mods were authored - Chicken Plucker has a master list of weapon defs, that he just copies and pastes in different combinations for each faction. 

So similarly, the patches for each set of RN item are self-contained, so that when CP releases another faction, we just copy and paste the various weapon/apparel patches from the larger RN Weapons and RN Clothing collection.

**Comment by sumghai** [comment]
I've patched the RN Clothing backpacks and harnesses - the armored vests from that mod already have the correct layers and body part coverage.

I'm going to take a look at the faction mods now.

**Comment by sumghai** [comment]
Faction mods have been patched as well - please let me know if I've missed anything, @Theblessedwant.

**Comment by Theblessedwant** [comment]
Everything looks about right

**Comment by sumghai** [comment]
Okie doke - closing.
