### ISSUE TITLE
Turned off Ammo in menu but still appearing in game and pawns reloading etc

### ISSUE THREAD

**Issue by xaitan** [AthenaSulisMinerva/CombatExtendedFastTrack#155]
Pretty much as the title says, I turned it off in main menu, when I get in game ammo options still show when selecting a pawn and they still reload etc.

**Comment by sumghai** [comment]
Did you start a new game after disabling the ammo system, or did you try reloading an existing game?

**Comment by xaitan** [comment]
Yes. I tried both. I also tried disabling ALL other mods and just running CE FT. No dice.

**Comment by sumghai** [comment]
What about with the original CE mod?

**Comment by xaitan** [comment]
Same thing.

**Comment by sumghai** [comment]
Right, this is unfortunately beyond the capabilities of the CE:FT team, since we simply pull the same base code as the original CE mod.

Could you please try raising this issue with the original CE team instead?
