### ISSUE TITLE
[Ods]Kaiser Reich's Imperial Army - Apparel & [Ods] Third Reich - Uniforms mod patches

### ISSUE THREAD

**Issue by skycrossercat** [AthenaSulisMinerva/CombatExtendedFastTrack#170]
They are the only WWI and WWII german apparel mods for now, it would be nice to use them with CE.
https://steamcommunity.com/sharedfiles/filedetails/?id=1339565361
https://steamcommunity.com/sharedfiles/filedetails/?id=1508927726
I know the whole CE:FT team is busy working on CE1.6 patch updates, so there's no hurry on this, thx.

**Comment by sumghai** [comment]
I recently came off patching apparel for CP's British Military Kit, so I'm familiar enough with the process to (possibly) be able to do this in time for our next update.

No firm promises, though, as we do have a backlog.

**Comment by sumghai** [comment]
Both patches have been tested and are good to go.

Ods defines his vanilla defs slightly differently from CP, so I had to play around with the armor rating stats a little to get sensible protection values.
