### ISSUE TITLE
READ ME FIRST - How To Report An Issue

### ISSUE THREAD

**Issue by sumghai** [AthenaSulisMinerva/CombatExtendedFastTrack#175]
# 1) Do some basic troubleshooting
Start a new, temporary savegame with only Core and CE:FT enabled, and verify that you don't have any problems.

You'll then need to test your other mods to narrow down the one(s) causing problems:
* If you only have a few mods, you can add them in one at a time, and reload the game each time until you come across the mod that's conflicting with CE:FT
* If you have hundreds of mods, then you will need to conduct a [binary search](https://en.wikipedia.org/wiki/Binary_search_algorithm):
  1. Keep Core and CE:FT loaded at all times
  2. Disable half of your mods
  3. Start a new, temporary savegame
  4. If there is no problem, disable the current half of mods and enable the other half
  5. If there is a problem, disable half of your current half of mods
  6. Reload the savegame
  7. Repeat steps 4 through 6 iteratively, until you narrow down the mod(s) causing the issues

# 2) Check if someone has already reported the issue
Chances are, you're not the first and only person to experience a particular problem, so use the search tool on the issue tracker home page to search for related keywords:
![Annotation 2019-11-27 222905](https://user-images.githubusercontent.com/4993380/69731732-5d207a00-1165-11ea-934d-465e99776de7.png)
If you find an open (or closed) issue that matches your problem, then just join the existing discussion - don't open a duplicate issue just to get our attention, because we'll have to close that to keep discussions streamlined.

# 3) Open a new ticket
If you don't find an existing issue describing your problem, then you can now submit your own ticket. 

**Remember - only one question/problem per issue ticket** - don't smush twenty or thirty  questions together, hoping we can fix them all in one sitting. Multiple questions per issue makes it harder to divide tasks amongst our team, as well as harder to mark which questions are duplicates of existing issues.

So that the CE:FT has enough information to investigate your problem, please make sure you include the following information:

* **A good, descriptive title** - the title should succinctly summarize your problem - e.g. `NewRatkinPlus apparel missing armor penetration stats`; don't write meaningless stuff like `problem`, `mods broken` or `plz help`, but we're not expecting long essays like `when i try to use android tiers the androids don't shoot and spin around like crazy i am frustrated i dont know what to do`, either
* **Operating System** - e.g. `Windows 10 64-bit`
* **RimWorld Version** - e.g. `1.0.2408 rev747`
* **CE FastTrack Version** - this can be found in our About.xml file - e.g. `1.0.1.8-FT-009`
* **The name(s) of the third-party mod that is causing the problem, if any** - If possible, also include the version number or update release date e.g. `Defensive Machine Gun Turret Pack, Version 1.5.2`; don't write `android tiers, latest version`, because we don't know what the latest version is
* **Details of the problem** - a good format to follow is:
   * What is the expected/correct behaviour? - e.g. `The M4 Carbine should have a magazine size of 30`
   * What is the actual behaviour? - e.g. `The M4 Carbine currently has a magazine size of 123`
   * Steps to reproduce the problem (how did you come across the problem?) - e.g. `I tried crafting one M4 Carbine at the Machining Table with 50 steel and 6 industrial components, and the resulting weapon had the wrong magazine size`
* **Include screenshots, error messages etc.** - you can directly drag and drop images to be embedded into your issue
* **If you are requesting a mod/ammo/race compatibility patch** - please provide a link to the original mod on GitHub or Steam Workshop; if you also know the link of an existing CE patch mod, that would be appreciated, too (we tend to rewrite and test patches ourselves, but it's always good to have a reference)

# 4) Wait for a response
The CE:FT team is very small compared to the original CE team, and we are spread across multiple timezones, so please be patient

# 5) If asked, provide additional information
Sometimes your initial report may not be enough to go on., and we may ask for more details or get you to try some more workarounds/debugging. Don't take this personally - we want to help you as much as possible, and the more information you provide us, the quicker we can narrow down the problem. 

**Note that if you do not follow up on a question/request within seven days, the CE:FT team reserves the right to close your issue unresolved, as we will assume that your lack of response indicates you already solved your problem on your own.**

Good Hunting!

**Comment by AthenaSulisMinerva** [comment]
Just added a rule regarding log files - they should be provided through Pastebin.

I had to trim an extremely long post from a user who pasted their entire log directly onto GitHub.

**Comment by AthenaSulisMinerva** [comment]
Updated OP with additional troubleshooting instructions and screenshot of the new issue template system.
