### ISSUE TITLE
Compatibility with Dual Wield

### ISSUE THREAD

**Issue by Christmas5** [AthenaSulisMinerva/CombatExtendedFastTrack#177]
Would it be possible to implement compatibility with the Dual Wield mod?
If not, what about making a CE version of it?

https://steamcommunity.com/workshop/filedetails/?id=1628211313

**Comment by AthenaSulisMinerva** [comment]
Dual Wield's author Roolo specifically said that it was too much work to make his mod CE compatible on his end, and none of us in the CE:FT team are C# wizards, so there's nothing we can do on our end, either.
