### ISSUE TITLE
Invisible HUD / Can't Click Bug

### ISSUE THREAD

**Issue by Nazgul96** [AthenaSulisMinerva/CombatExtendedFastTrack#179]
Windows 7 32 bit / Rimworld Ver. 1.0.2059 / CE:FT Ver. 1.0.1.8-FT-010
When i install this mod, my HUD disappears and i can't click on anything. All the game shows me is my colonist mood bars on the top. The only key that works is Space (pause, unpause). Can't even press Esc. Problem persists even if i only load the core in the mod settings. I even deleted every other mod from the folder.

**Comment by sumghai** [comment]
Windows 7 32-bit? That's a fairly old OS, and it seems like you don't have a lot of memory in your PC as well.

Do you experience the same problem with the original CE mod?

**Comment by Nazgul96** [comment]
I does happen with the original CE. So far it is the only mod that causes problems in a list with 50+ mods

**Comment by sumghai** [comment]
In which case, I suggest you report this issue to the upstream CE repo's issue tracker, as this is beyond the capabilities of the FastTrack team.
