### ISSUE TITLE
Support for Kijin Race 2.0 Patch Request

### ISSUE THREAD

**Issue by pecg8237** [AthenaSulisMinerva/CombatExtendedFastTrack#181]
It's race mod and added new weapons and apparels.It works great with Medieval Times mod.When you have time to patch Medieval Times, hope to work on this mod together. Here is the link https://steamcommunity.com/sharedfiles/filedetails/?id=1918120749&searchtext=kijin

**Comment by AthenaSulisMinerva** [comment]
Thanks for letting us know. We'll look into it when we have time.

**Comment by skycrossercat** [comment]
[https://github.com/NoImageAvailable/CombatExtended/pull/921](url)
Looks like upstream CE is working on Kijin 2.0 already.

**Comment by AthenaSulisMinerva** [comment]
Good - CE:FT can focus on other patches.

**Comment by AthenaSulisMinerva** [comment]
Already included in FT-013.
