### ISSUE TITLE
7.92x57mmMauser defName correction request to upstream CE

### ISSUE THREAD

**Issue by skycrossercat** [AthenaSulisMinerva/CombatExtendedFastTrack#184]
Is it possible to contact upstream CE authors to correct the defName of  7.92x57mmMauser? It's quite weird to see that the label of it is the correct one but the defName is 7.92x51mmMauser.
And the most important problem is that if other authors try to make CE patches in their own (weapon) mods, they would need to make two separate versions just because of single defName difference. Since most CE patches are made for original CE, they may not work for CE:FT users.

**Comment by AthenaSulisMinerva** [comment]
@sumghai, I know you're uncomfortable dealing with upstream CE team, but since you already have a personal fork of said upstream, could you please do the needful?

**Comment by sumghai** [comment]
I submitted a PR last night, so it's up to them now.

**Comment by sumghai** [comment]
No response from their end.

Since we've done our due diligence, there's nothing more to do here.
