### ISSUE TITLE
Support for Swords Patch Request

### ISSUE THREAD

**Issue by RC311** [AthenaSulisMinerva/CombatExtendedFastTrack#187]
The autor already made CE patch can you check?
https://steamcommunity.com/sharedfiles/filedetails/?id=1845180112

**Comment by skycrossercat** [comment]
@RC311 You better send the update request to the author instead since it already has its own CE patch. Otherwise, it may cause duplication when both CE:FT and the original mod update the patch to the current CE version.

**Comment by AthenaSulisMinerva** [comment]
@skycrossercat is correct.

If a mod author has already bundled CE patches into their original mod itself, then it is up to the author to keep their patches updated.

CE:FT generally patches mods that either don't have CE patches at all, or if the patches exist as standalone "patch" mods.

In the interest of avoiding patching conflicts/duplications, we're most likely not going to handle this one (unless the author suddenly decides to remove CE compatibility).
