### ISSUE TITLE
[RH] Faction: The Ghosts- Tacticool Doggo CE1.6 Patch submit

### ISSUE THREAD

**Issue by skycrossercat** [AthenaSulisMinerva/CombatExtendedFastTrack#189]
I've made a CE1.6 patch for German Shepherd of the ghost, can you merge it into the CE:FT? I just tweak some value to make it work with new CE armor mechanics, also make the dog attack slightly faster, but less powerful compared to vanilla wolfs.
here's the link:
https://drive.google.com/open?id=1vaSWEeWTFr3KumT105tPk9N_NjnN5-1z

**Comment by sumghai** [comment]
Patch updated. Many thanks for the help!
