### ISSUE TITLE
nation clothing patch cant use

### ISSUE THREAD

**Issue by HUDAXIAND** [AthenaSulisMinerva/CombatExtendedFastTrack#190]
![QQ截图20191205040917](https://user-images.githubusercontent.com/57340572/70177490-6eddc080-1715-11ea-8ed7-281fa30d3457.png)
![QQ截图20191205041010](https://user-images.githubusercontent.com/57340572/70177501-7309de00-1715-11ea-917c-159d6f06999e.png)
the patch cant use but nation weapon can use

**Comment by skycrossercat** [comment]
Have you ever test it yoirself that the patch is unplayable or just report this cause you see the red letter? You don't even describe how the problem looks like.
The red letter is mean to tell you that some outdated data is disabled to prevent some errors.

**Comment by sumghai** [comment]
@skycrossercat, this is a Chinese user who probably doesn't understand the context of the warning message in English - I can handle this one.

**简而言之:** 不必管那个错误信息，您其实还是可以在 CE:FT 用 RN Clothing

**解释:** 有一些服饰模组 (包括 RN Clothing) 里面包含了一个未跟新的 GraphicApparelDetour.DLL，会跟 CE 新的服装层数码发生冲突。为了使用户的安全, CE:FT 将自动禁用那个DLL，可是 RN Clothing 主要部分可以继续用。本错误信息只是提醒您去跟 GraphicApparelDetour.DLL 的作者去投诉，请他更新数码来符合 CE:FT.

(注：这一次为了您的方便用简体中文回你，以后在本GitHub上请只用英文。谢谢您的配合。）

---------------

**In short:** Don't worry about that error message, you can still use RN Clothing in CE:FT

**Explanation:** Many apparel mods such as RN Clothing comes bundled with an outdated assembly called GraphicApparelDetour.DLL, which is incompatible CE's new apparel layer system. CE:FT automatically disables that DLL, but will allow you to keep using the rest of RN Clothing itself. The warning message is just for you to tell the author of GraphicApparelDetour.DLL to please update his code to be compatible with CE:FT.

(Note: For your convenience this one time, I am replying to you in Simplified Chinese, but in the future please only use English on GitHub. Thank you for your understanding.)
