### ISSUE TITLE
[Pratt] WWII weapon pack Turrets defName change and updates

### ISSUE THREAD

**Issue by skycrossercat** [AthenaSulisMinerva/CombatExtendedFastTrack#195]
CE:FT version: v1.0.1.8-FT-011
The recent update of [Pratt] WWII weapon pack (12/8) changed all turrets' defName from MG to HMG (ex: Turret_MG34MG ->Turret_MG34HMG), causing the current patch from CE:FT invalid. This problem also happens to its own graphic set up in architect menu, not sure how the author gonna fix this.
This update also adds some new weapons, needs some minor updates to the patch.
https://steamcommunity.com/sharedfiles/filedetails/changelog/1894552878

**Comment by sumghai** [comment]
> The recent update of [Pratt] WWII weapon pack (12/8) changed all turrets' defName from MG to HMG (ex: Turret_MG34MG ->Turret_MG34HMG), causing the current patch from CE:FT invalid.

Oh, bother.

> This problem also happens to its own graphic set up in architect menu, not sure how the author gonna fix this.

Yeah, this isn't the first time Pratt's rushed changes through without thinking about how they affect other parts of his own mod.

> This update also adds some new weapons

Okay, I'll add those when I have time

(ASIDE - I've noticed you've been inserting URLs incorrectly in your issue tickets. All you need to do is to copy and paste the raw URL, and GitHub's markdown will automatically turn it into a working link.

The "Add a link" button is only used if you want to hide the URL behind a string of text 

e.g.
```
[A link that goes somewhere](https://steamcommunity.com/sharedfiles/filedetails/changelog/1894552878)
```
results in

[A link that goes somewhere](https://steamcommunity.com/sharedfiles/filedetails/changelog/1894552878)

**Comment by skycrossercat** [comment]
Alright, the author(Pratt) just pushes a quick update to change the defName back to the old one, which means the patch is working again.
And I found why the textures in architect menu failed to present and report it to him as well.

> The "Add a link" button is only used if you want to hide the URL behind a string of text
Ok, thx for telling me that.

**Comment by sumghai** [comment]
Mucho gracias!

I'll leave this ticket open until the new items are patched, whenever I can get around to it :)

**Comment by sumghai** [comment]
These are good to go for the next update.
