### ISSUE TITLE
NewRatkinPlus patch need update

### ISSUE THREAD

**Issue by HUDAXIAND** [AthenaSulisMinerva/CombatExtendedFastTrack#196]
XML error: Duplicate XML node name apparelRequired in this XML block: <PawnKindDef ParentName="RKBasePawnKind"><defName>RatkinEliteGuardener</defName><label>ratkin Elite Guardener</label><baseRecruitDifficulty>0.95</baseRecruitDifficulty><combatPower>50</combatPower><isFighter>true</isFighter><itemQuality>Good</itemQuality><backstoryCategories><li>RatkinGuardener</li></backstoryCategories><apparelMoney><min>3500</min><max>4500</max></apparelMoney><gearHealthRange><min>0.5</min><max>0.8</max></gearHealthRange><apparelRequired><li>RK_GaurdenUniform</li></apparelRequired><weaponMoney><min>3000</min><max>5000</max></weaponMoney><weaponTags><li>RK_Sword</li><li>RK_Rifle</li><li>RK_CrossbowAdvanced</li></weaponTags><apparelTags><li>RK_Gaurdener</li></apparelTags><apparelAllowHeadgearChance>0.0</apparelAllowHeadgearChance><apparelRequired><li>RK_GaurdenUniform</li></apparelRequired></PawnKindDef>
Verse.Log:Error(String, Boolean)
Verse.XmlInheritance:CheckForDuplicateNodes(XmlNode, XmlNode)
Verse.XmlInheritance:ResolveXmlNodeFor(XmlInheritanceNode)
Verse.XmlInheritance:ResolveXmlNodesRecursively(XmlInheritanceNode)
Verse.XmlInheritance:ResolveXmlNodesRecursively(XmlInheritanceNode)
Verse.XmlInheritance:ResolveXmlNodes()
Verse.XmlInheritance:Resolve()
Verse.LoadedModManager:ParseAndProcessXML(XmlDocument, Dictionary`2)
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.Root:<Start>m__1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__1()
![QQ截图20191208155517](https://user-images.githubusercontent.com/57340572/70386325-2ce1a280-19d3-11ea-99b3-9a71849bf291.png)

**Comment by sumghai** [comment]
Please follow the correct bug reporting guidelines:

https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/issues/175

**Comment by skycrossercat** [comment]
I think he doesn't really understand English, so I will answer him in Chinese (hope he can read traditional Chinese cause I can't type simplified one).

@HUDAXIAND  Ratkin的CE:FT 版本還沒有更新到1.6的數值，所以在CE1.6的架構下是用不了的，如果你真的有急需的話，工作坊上可以找到Ratkin的獨立CE補丁，如果要跟CE:FT共用的話記得手動移除CE:FT裡的Ratkin補丁，但那補丁有些小問題還沒修正，也只能等作者改善。
還有一個問題是你的MOD排序是錯誤的，CE應該要放在Alien Race2.0後面；外星種族的MOD之前。

如果你真的不懂英文也沒關係，但這裡畢竟是個英文社群，那怕是用翻譯機也好也要盡可能用英文描述出問題，不然大家也沒辦法幫你解決。另外，也要盡可能提供像是CE:FT的版本號之類的訊息，越詳細且正確的訊息都能讓大家更快幫你解決問題。

I just told him that the ratkin patch in CE:FT is not updated yet, if he needs it now, he can use the N7HuntsMan's version on workshop, but needs to delete the ratkin patch in CE:FT first.
And some other load order issue, try convince him to follow the rule here etc.

**Comment by sumghai** [comment]
Mucho gracias for helping out, @skycrossercat :)

I can type in both Traditional and Simplified Chinese, but based on his screenshot I suspect he's from Mainland China, and so will probably struggle with Traditional.

**Comment by AthenaSulisMinerva** [comment]
I don't speak Chinese, but can you please provide the information @sumghai and @skycrossercat are asking, @HUDAXIAND?

**Comment by songtransporter** [comment]
@AthenaSulisMinerva Recent update for NewRatkinPlus added <apparelRequired> tag to Ratkin Elite Guardner. That's the problem.

**Comment by AthenaSulisMinerva** [comment]
Thanks for the info, @songtransporter - I'll take a look tomorrow night.

**Comment by sumghai** [comment]
Fixed for the next release.

@HUDAXIAND - in the future, please follow [the instructions for reporting bugs](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/issues/175) in the right way.

**Comment by AthenaSulisMinerva** [comment]
Should be fixed now.

**Comment by skycrossercat** [comment]
This might be some other issue, but just a reminder: The apparels' armor value, melee tools' armor penetration (from Race and Weapons patch) are outdated.

**Comment by sumghai** [comment]
No, you're quite correct, @skycrossercat - since the title of the OP is general enough, I'm going to let this one slide by reopening this issue and repurposing it for the stat updates.

@AthenaSulisMinerva - please note that because of the unique physical geometries of various Ratkin melee tools, you will most likely need to recalculate melee and penetration stats from scratch using our spreadsheets and educated guesses on blade/cutting edge length/width/thickness, instead of simply copying and pasting values from other weapons.

**Comment by AthenaSulisMinerva** [comment]
That's fine @sumghai, but we'll make this exception _just this once_.

I'll see what I can do, while you currently don't have access to Google services.

**Comment by AthenaSulisMinerva** [comment]
Okay, this is finally done.
