### ISSUE TITLE
Some mods that were in the past patched

### ISSUE THREAD

**Issue by lucianfallen** [AthenaSulisMinerva/CombatExtendedFastTrack#197]
[CP] Rimmu-Nation - Clothing (All Craftable!) (1.0)
[CP] Rimmu-Nation - Gloves N' Boots (1.0)
[CP] Red Horse Furniture (1.0)
[RH] Faction: Elite Crew (1.0)
[RH] Faction: Last Man Mercs (1.0)
[RH] Faction: Militaires Sans Frontieres (1.0)
[RH] Faction: Task Force 141 (1.0)
[RH] Faction: Umbra Company (1.0)
[RH] Faction: The Ghosts (1.0)

**Comment by sumghai** [comment]
These mods are still currently supported by CE:FT - what issues are you experiencing with them?

**Comment by lucianfallen** [comment]
https://imgur.com/a/1NqcpFO

**Comment by sumghai** [comment]
The patches for those mods still work just fine.

The error message simply means that the `GraphicApparelDetour.dll` that comes with those mods has been turned off by CE:FT, as it is outdated and caused the pink square issue in the past. It is up to whoever gave Chicken Plucker that version of `GraphicApparelDetour.dll` to fix the DLL, not Chicken Plucker or the CE:FT team.

This was explained quite clearly in the releases notes in the past.
