### ISSUE TITLE
New preview pic

### ISSUE THREAD

**Issue by AthenaSulisMinerva** [AthenaSulisMinerva/CombatExtendedFastTrack#2]
We need a new preview picture for the mod info About.xml and the Steam release, so that people don't mix this up with the old CE mod.

@sumghai you did the Rimmu-Nation graphics. Can you do a banner for us?

**Comment by sumghai** [comment]
Yeah, sure. What do you have in mind?

**Comment by AthenaSulisMinerva** [comment]
Something crisp and fresh. And lose the Mexican hat guy.

**Comment by sumghai** [comment]
> Something crisp and fresh.
That's not really much to go on, but I'll see what I can do. I'm a bit busy this week.

> And lose the Mexican hat guy.
Okay, no Sombrero.

**Comment by sumghai** [comment]
> Something crisp and fresh.

That's not really much to go on, but I'll see what I can do. I'm a bit busy this week.

> And lose the Mexican hat guy.

Okay, no Sombrero.

**Comment by sumghai** [comment]
Okay, just put something up. Sorry for the delay.

**Comment by AthenaSulisMinerva** [comment]
Nice work! Thanks.
