### ISSUE TITLE
Turn the fork into just a set of patchs without a CE core or make separate edition with just patchs for original CE?

### ISSUE THREAD

**Issue by Taranchuk** [AthenaSulisMinerva/CombatExtendedFastTrack#20]
Today I switched to Fast Track, deleted the original, launched the game, and found that some of the old patches for CE in other mods stopped working and I got a bunch of red errors. The reason as I understood that the fork uses a new mod name, and the patches are looking for a mod by the name 'Combat Extended', not 'Combat Extended: Fast Track'. Since there are too many patches and although I can massively replace all the names with a new one, there is an Steam auto-update and the files will be overwritten, this is not an option. In case the fork developers do not plan to change and add the mechanics of the CE mod, then why not just turn the fork into just a set of patches for CE, so that both old and new patches can coexist without errors? Or you can make a separate edition, which includes just a set of patches for original CE and continue to develop fork.

**Comment by TheEventHorizon** [comment]
Just go into the files of CE:FT and edit the name of of the mod in the about file from `<name>Combat Extended: FastTrack Edition</name>` to `<name>Combat Extended</name>`.

**Comment by Taranchuk** [comment]
I can do this, just change one file, this is not a problem. But the fact is that there may be other users who have other patches for CE and these patchs will stop working if they decide to switch to a Fast Track fork and they may not be aware of this solution, that's the problem. The question is, what policies do fork developers prefer, will they decide to do something about it or not.

**Comment by AthenaSulisMinerva** [comment]
The intention of this fork is to bundle as many third-party compatibility patches as possible, and add new ammo types as required, so that users don't have to worry about standalone patches or mod orders - they just get CE:FT and the main mods they play with, and that's it. 

We originally did want to submit a collection of patches to the original CE project, but the original project's authors repeatedly rejected our pull requests for personal reasons. This is why we had to stick out on our own.

There's no point in turning CE into a patches-only compilation, either, as there are other groups that do that already.

I don't know if there is a good solution to deal with supporting patches written specifically for the original CE, though.

**Comment by sumghai** [comment]
What about the following compromise?

Revert the mod name in the About.xml back to just "Combat Extended", but we keep the full "Combat Extended: FastTrack Edition" name for the folder, README, preview pic, @Freedom187's Steam Workshop release etc.

That way it should be obvious to newbie users that they're using the FastTrack fork, but ensures backwards compatibility with legacy third-party patches. This doesn't preclude us from soliciting and assimilating those third-party patch mods later down the line, but would at least help us retain the goodwill of the community (especially if we were to truly market ourselves as a drop-in replacement)

**Comment by AthenaSulisMinerva** [comment]
Fair point.

@Taranchuk, what do you think of @sumghai's suggestion?

**Comment by Taranchuk** [comment]
I like this suggestion, it solves problems with compatibility of patches and allows you to develop fork.

**Comment by AthenaSulisMinerva** [comment]
@Taranchuk, please test this exact dev build with your other CE patch mods:

https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/archive/3533cbb3e6465ef7b26a8c8fff1d4875a30bb61a.zip

**Comment by Taranchuk** [comment]
Yesterday I already changed the mod name in About.xml and started the game, the red errors disappeared and everything works fine. But I will download your dev mod and try to run it again, but you have to wait, my huge mod list loads for a long time.

**Comment by Taranchuk** [comment]
Sorry for the delay, I had to leave home about my business. I started the game now, no red errors appeared, the game works fine, the dev build works fine.

**Comment by AthenaSulisMinerva** [comment]
Excellent.

I'll probably push out an update with these changes soon.
