### ISSUE TITLE
Nightling from the Forsakens mod causes Red Error

### ISSUE THREAD

**Issue by Nubasik** [AthenaSulisMinerva/CombatExtendedFastTrack#201]
Hello! I am writing here for the first time. Sorry in advance for my English, I'm from Russia. I want to say a big thank you to the CE-FT team and the original CE team for this great mod.
There was a small problem when using the Forsakens mod.
OC - Win-7 64-bit
RimWorld Version - 1.0.2408 rev747
CE FastTrack Version - 1.0.1.8-FT-012
Mod - Forsakens v.1.7 [https://github.com/Kik0hi/Forsaken/releases](url)

Creature call through development mode red error appears.
Trying to get stat MeleeArmorPenetration from NightlingF which has no support for Combat Extended FastTrack Edition.
Verse.Log:Error(String, Boolean)
CombatExtended.StatWorker_MeleeArmorPenetration:GetStatDrawEntryLabel(StatDef, Single, ToStringNumberSense, StatRequest)
RimWorld.StatDrawEntry:get_ValueString()
RimWorld.StatDrawEntry:Draw(Single, Single, Single, Boolean, Action, Action, Vector2, Rect)
RimWorld.StatsReportUtility:DrawStatsWorker(Rect, Thing, WorldObject)
RimWorld.StatsReportUtility:DrawStatsReport(Rect, Thing)
Verse.Dialog_InfoCard:FillCard(Rect)
Verse.Dialog_InfoCard:DoWindowContents(Rect)
Verse.<WindowOnGUI>c__AnonStorey0:<>m__0(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)
Screenshots:
https://d.radikal.ru/d20/1912/fd/0169a9722d6f.png
https://b.radikal.ru/b07/1912/67/204955ff341b.png

I understand how much time and effort you put into work, and it’s unrealistic to check every little thing. But I really do not want to give up my favorite mods. I wish you success in the development of your mod.

**Comment by AthenaSulisMinerva** [comment]
Thanks for letting us know! I'll take a look at this one in a moment.

**Comment by AthenaSulisMinerva** [comment]
Should be fixed now - this will be included in our next update.
