### ISSUE TITLE
Lizardmen and CE-FT. Causes red errors

### ISSUE THREAD

**Issue by ghost** [AthenaSulisMinerva/CombatExtendedFastTrack#205]
When you turn on the mod, it causes red errors.
OC - Win-7 64-bit
RimWorld Version - 1.0.2408 rev747
CE FastTrack Version - 1.0.1.8-FT-012
Mod - Lizardmen [https://steamcommunity.com/sharedfiles/filedetails/?id=1710060170](url)

Log
[https://gist.github.com/HugsLibRecordKeeper/d549840765fb545ba5b6b187d3ef48cb](url)

Screenshot
![2019-12-15_191047](https://user-images.githubusercontent.com/58890215/70865974-bb769680-1f74-11ea-9129-b5ed74bd0083.png)
![2019-12-15_191007](https://user-images.githubusercontent.com/58890215/70865977-c03b4a80-1f74-11ea-9d22-4145287fdba9.png)
![2019-12-15_215353](https://user-images.githubusercontent.com/58890215/70867389-f1704680-1f85-11ea-9497-1f27339cf762.png)

**Comment by sumghai** [comment]
It looks like @OwlChemist decided to bundle his own CE patches inside his Lizardmen mod, which is what's conflicting with CE:FT's patches. In the long term, CE:FT may have to consider removing integrated support for Lizardmen.

@ghost, a quick workaround might be to delete the Lizardmen patches from CE:FT, and let Lizardmen's own CE patches take over. Try that and see how it goes.

**Comment by AthenaSulisMinerva** [comment]
Related to #206, as @OwlChemist authors both mods and his bundled patches could potentially make our integrated patches obsolete.

**Comment by sumghai** [comment]
Same course of action as described [here](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/issues/206#issuecomment-569935426).

**Comment by AthenaSulisMinerva** [comment]
Lizardmen patches have now been removed at @Owlchemist's request - any compatibility issues with CE:FT will now be his sole responsibility.
