### ISSUE TITLE
Yabils and CE-FT. Causes red errors.

### ISSUE THREAD

**Issue by ghost** [AthenaSulisMinerva/CombatExtendedFastTrack#206]
When you turn on the mod, it causes red errors.
OC - Win-7 64-bit
RimWorld Version - 1.0.2408 rev747
CE FastTrack Version - 1.0.1.8-FT-012
Mod - Yabils: Space Gremlins [https://steamcommunity.com/sharedfiles/filedetails/?id=1711219414](url)

Log:
[https://gist.github.com/e290b1e2ee35a6d489a5f3533cc148bd](url)

Screnshots
![2019-12-15_201954](https://user-images.githubusercontent.com/58890215/70866243-60df3980-1f78-11ea-90d1-588bef86202f.png)
![2019-12-15_201921](https://user-images.githubusercontent.com/58890215/70866246-650b5700-1f78-11ea-8a0f-71be435a043e.png)
![2019-12-15_214447](https://user-images.githubusercontent.com/58890215/70867356-a8b88d80-1f85-11ea-83bc-c6c2ba1b3ab4.png)

**Comment by skycrossercat** [comment]
You better check if the patch is outdated or not before load it, especially after some big CE updates. CE1.6+ changes a lot of value and mechanics, which makes almost all the patches need some reworks. Both Alien patches you report are outdated (last update 5 months ago), so it's normal to have compatibility issues.

**Comment by Nubasik** [comment]
OK. Thanks for the help.

**Comment by skycrossercat** [comment]
You can still keep these issues open to remind CE:FT team to update the patches, no rush to close them.

**Comment by sumghai** [comment]
It looks like @OwlChemist decided to bundle his own CE patches inside his Yabils mod, which is what's conflicting with CE:FT's patches. In the long term, CE:FT may have to consider removing integrated support for Yabils.

@ghost, a quick workaround might be to delete the Yabils patches from CE:FT, and let Yabils' own CE patches take over. Try that and see how it goes.

**Comment by AthenaSulisMinerva** [comment]
It's a mixed blessing, really - on one hand, it sucks that we have to drop support for this mod and reduce our running tally of supported mods, but on the other hand, having the author handle patches themselves means one (or two) less mods to worry about.

@sumghai - please contact @OwlChemist and ask if he wants us to remove patches for all his mods from CE:FT.

Also, we should probably patch some more (other) mods to maintain our tally.

**Comment by sumghai** [comment]
I've left a message on @OwlChemist's Steam Workshop pages for this mod, and I'll follow up again in a week if I don't hear back from him.

Worst case scenario would be to just drop support without explicitly obtaining permission, and probably remove his name from the acknowledgements section in the README.

**Comment by sumghai** [comment]
@Owlchemist has advised us to remove our patches for his mods.

While hasn't updated his own patches to support the armor penetration stat changes from CE 1.6/1.8+, our patches will regardless always clash with his.

**Comment by AthenaSulisMinerva** [comment]
Fair enough - I'll delete them tomorrow morning.

Let's hope the new mods you are working on patching will make up for the shortfall.

**Comment by AthenaSulisMinerva** [comment]
Yabils patches have now been removed at @Owlchemist's request - any compatibility issues with CE:FT will now be his sole responsibility.
