### ISSUE TITLE
Recipe for 5x35mmCharged

### ISSUE THREAD

**Issue by NickZiggy** [AthenaSulisMinerva/CombatExtendedFastTrack#209]
5x35mmCharged is missing a recipe and the CE_AutoEnableCrafting trade tag. I need it for my CE:FT-addon which makes the Charge Lance usable for humans.

**Comment by NickZiggy** [comment]
Made a pull request for this.

**Comment by sumghai** [comment]
Since you've already made a PR, I'll review it over there and close this issue.
