### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by Flippy1** [AthenaSulisMinerva/CombatExtendedFastTrack#21]
Of course this is the pipe dream and probably flat out impossible but i want to ask anyway, is it possible to get a MP patch.

**Comment by AthenaSulisMinerva** [comment]
The CE:FT team only does compatibility patches for weapons and ammo, not in-depth API or assembly code changes.

And it looks like it's something that the Multiplayer mod team has to do on their end anyway (Parexy/Multiplayer/issues/36)
