### ISSUE TITLE
Zombieland & CE/CE:FT Conflict

### ISSUE THREAD

**Issue by Meronmero** [AthenaSulisMinerva/CombatExtendedFastTrack#212]
This doesn't generate any errors on the log.
Pawns and turrets will aim and shoot at walls when zombies are on the other side.
It will not do this for regular enemies such as Hostile Ancient Soldiers.

Tested using 3 mods.
[Mod Manager, CE, Zombieland]
[Mod Manager, CE:FT, Zombieland]

Both versions of CE cause this issue. Because turrets keep retargeting it causes a ton of lag when they're activated with zombies in their range.

**Comment by AthenaSulisMinerva** [comment]
This issue most likely lies with whoever wrote the original patch in the upstream CE mod, from which CE:FT pulls its updates from.

**Comment by Meronmero** [comment]
Should I report his on the CE github then?

**Comment by sumghai** [comment]
Might be a good idea to do so.
