### ISSUE TITLE
Disabling the suppression system?

### ISSUE THREAD

**Issue by Nutellaschmier** [AthenaSulisMinerva/CombatExtendedFastTrack#214]
Since I do not find any solves for that on steam and people on github keep blaming me for not trying right when opening a discussion, I go with this question to the developer directly and the people here.

I dont want to sound rude, but I want to disable the supression system, so people stop running in circles away instead of just shooting the gunner down with theire 200 bullets legendary machine gun while wearing a marine armor. You can literally hold back 50 tribal melees just by making them run around a tree. But I am not here for critisim, since I like the mod and wouldnt want to play without it again, finally people are able to hit things and the shooting skills finally matter, no random bullshit missing chance anymore. 
So just this question: Does anyone know, how to disbale supression in the xml files. 
I tried un-commenting the two jobs: "RunforCover" and "HunkerDown" and it worked so far that people stopped hunkering down and running for cover, but now they instead (the icon of "being supressed" is still there just stand there and theire actual job task sais :"Waiting"...
I not that big of a modder, only have basic xml knowlegde, but there are only xml files anyway.
So, this is really not meant to be an as*-move, I really enjoy the mod, I am just hoping to get help from the developer himself, rather then being spit and insulted on in the github discussion.

**Comment by skycrossercat** [comment]
That should be a base CE feature, CE:FT team only adds some compatibility patches for third-party mods, instead of asking it here, you should go ask original CE team IMO.

**Comment by Nutellaschmier** [comment]
Ok. Just thought since they pürogramming this mod too they know how that works. I guess I take a look over there, thanks

**Comment by AthenaSulisMinerva** [comment]
As @skycrossercat correctly explained, suppression is a feature from the original CE mod. We suggest you ask the actual developers of the original CE mod for an option to disable suppression instead.

None of the CE:FT team are "programmers" or "devs" - the CE:FT fork mainly focuses on adding compatibility patches for mods not supported by the original CE mod due to political reasons.
