### ISSUE TITLE
Red Horse Factions: Rename LMM to [RH] Last Man Contingent, add new items

### ISSUE THREAD

**Issue by ChickenPluckers** [AthenaSulisMinerva/CombatExtendedFastTrack#217]
Hey fellers, I love you AthenaSulisMinerva (don't tell sumghai I said that cause he gets easily jealous)

I changed the mod name of Last Man Mercs into:
[RH] Faction: Last Man Contingent (1.0)

There is a new weapon added:
RNMeleeWeapon_Knife_Shiv

It's basically a knife.

New armor and helmet added:
RNApparel_FASTHelmetLMCT
RNApparel_HVYArmor_LMCT

A few new outfits, not sure if that matters but whatever. Here are the important stuff, hope you guys have a Merry Christmas.

Link to G Drive
https://drive.google.com/open?id=1zB3NTjisUFKr4hKk7C66RhWHeJJ_RhDP

Cool lore reasons, plot plot plot, texture update, texture update. Typey type type. Thanks for your hard work guys, take care

**Comment by AthenaSulisMinerva** [comment]
Hahahaha. I'll get @sumghai to do this along with #200.

On a more serious note, are you sure you won't be renaming your other mods or changing existing defnames? It's rather inconvenient dealing with sudden renamings breaking patches, as we've experienced with Pratt's WWII Weapons mod.

**Comment by sumghai** [comment]
Yeesh, @ChickenPluckers, you sure ain't making things any easier for us.

The wifi in my entire building has been down for over a week, and I cannot access Google Drive or Steam Workshop via my mobile data connection. It will be a while before I finish the current batch of patches for mods I have already downloaded (unless you've also updated those as well in the meantime).

Echoing @AthenaSulisMinerva's comment, please avoid arbitrarily renaming your mods in the future, as these break existing patches - the more time we spend renaming/reworking existing patches, the less time we have to support your other new mods.

**Comment by sumghai** [comment]
Will eventually handle this as part of #200, once I have a stable internet connection again.

**Comment by ChickenPluckers** [comment]
Hey guys, I understand. This is a one-time thing for this faction. Thank you!

Sumghai using up all the data in your building, finna need to calm down on the patches and have a holiday my friend. Take care guys
