### ISSUE TITLE
[RH] Faction: Cordis Die (1.0) - CLAW AGR health and armor rating nerf

### ISSUE THREAD

**Issue by ChickenPluckers** [AthenaSulisMinerva/CombatExtendedFastTrack#220]
Oof, nother update lads.

Just nerfed the CLAW AGR really:
Race: RHRace_CLAW_AGR
```
<ArmorRating_Blunt>0.30</ArmorRating_Blunt>
<ArmorRating_Sharp>0.60</ArmorRating_Sharp>

<baseHealthScale>2.0</baseHealthScale>
```

I've nerfed the armor ratings and base health scale for this fella, not sure if it's worth reporting here but I can never be too sure. Don't want the CE FT users hangin' out trying to kill the thing when I nerfed it already. Cheers guys, take care

**Comment by AthenaSulisMinerva** [comment]
You will have to wait until sumghai has stable internet access again, before he can look into your issue.

**Comment by sumghai** [comment]
Cordis Die patches are scheduled for #200, and since I haven't started on this yet, I'll work on this over there and close this as a duplicate issue.
