### ISSUE TITLE
Instant killing Traps

### ISSUE THREAD

**Issue by Nutellaschmier** [AthenaSulisMinerva/CombatExtendedFastTrack#222]
Hey,

I only found a semi discussion on steam about this, but since you have to submit this stuff on github, I report it here. It seems like the spike trap is instantly killing everything. Not even everything from mods, even the invincible Gallatross, also centipides and marine armor wearing pirates on go-juice. It isnt game breaking since, later in the game, (now that pawns, thanks to CE, are finally able to hit targets) I am not using wood traps anyway, using turrets and guns. But for the beginning of the game you somehow dont want to use them and for that being defensless because they are(in that state) more op then the "Glitterworld-Tech" mod. 

So, is there already a patch for that I overlooked? If not, may you look into that issue or give me a tip how to resolve it using the data inside mod folders. 
Thanks ahead for looking into this issue. Btw, my other discussion about disabling the suppressing was resolved by the beautiful tipp of just forcing "fearless" trait on all world pawns using scenario editor, so if somone else comes up with this, maiby you can tell them this tipp.

Greetings,

Joel Ernst

**Comment by AthenaSulisMinerva** [comment]
This is an issue from the original (base) CE mod, and is unfortunately outside our area of expertise.
