### ISSUE TITLE
[CP] Red Horse Furniture (1.0) - FBI Update

### ISSUE THREAD

**Issue by ChickenPluckers** [AthenaSulisMinerva/CombatExtendedFastTrack#223]
Hello again Athena, hope you're well.

https://imgur.com/nnNROHg
(Added an FBI event that triggers for the mod)

I've added a few new items:
RNApparel_FASTHelmet_HRT (Helmet)
RNApparel_PointBlank_FBI (Armor)
RNApparel_combats_SmockHRT (Onskin)

Also put in these weapons from the HRT set in Rimmu-Nation: 
(already patched by you guys, but not for this mod)
RNGun_M24A2HRTSn
RNGun_HK417HRTDMR
RNGun_MP5A2SDHRT_PDW
RNGun_UMP45HRT_PDW
RNGun_Remington870HRT
RNGun_M4A1HRT
RNGun_G36CHRT

I'm excited to finally implement these features, but at the same time feel a bit bad having add more to your workload. Whatever's the case thank you and I hope you have a Happy New Year. Sumghai hope you're safe and sound bro.

**Comment by AthenaSulisMinerva** [comment]
Sorry @sumghai, another one for you.

**Comment by sumghai** [comment]
I'll slip this into #200 

@ChickenPluckers - Due to our current workload for all your other pre-existing requests, I'm instituting a cutoff right here - any further RN / RH / CP requests from this point on will be pushed to Batch 4 (the update after the next one).
