### ISSUE TITLE
Unable to Fire Shots from Weapons; red error occurs

### ISSUE THREAD

**Issue by BValon** [AthenaSulisMinerva/CombatExtendedFastTrack#225]
OS: Windows 10 64-bit
Rimworld Version: 1.0.2059
CE:FT Version: 1.0.1.8-FT-012
Details:
**What is the expected/correct behaviour?**
To aim and fire a round at a target, in which the round exits the barrel of the weapon, traveling towards its target, and hopefully hits it.
**What is the actual behaviour?**
The pawn reloads the weapon, attempts to fire at its target, then a red error occurs, the magazine empties, and the pawn goes to reload and try again.
**Steps to reproduce the problem (how did you come across the problem?)**
This problem occurred during regular gameplay of a colony, and I have been testing to see what the problem stems from, to find it comes from CE:FT itself. A reinstall will temporarily fix it, but will eventually break on its own again.
https://gist.github.com/HugsLibRecordKeeper/f4da72681639c215527276066d447cf6
Related Error at moment of firing:
> Exception ticking Pan (at (101, 0, 134)): System.InvalidCastException: Cannot cast from source type to destination type.
> at CombatExtended.Verb_LaunchProjectileCE.TryCastShot () <0x0025e>
> at CombatExtended.Verb_ShootCE.TryCastShot () <0x00087>
> at Verse.Verb.TryCastNextBurstShot () <0x0006c>
> at Verse.Verb.WarmupComplete () <0x0003b>
> at CombatExtended.Verb_LaunchProjectileCE.WarmupComplete () <0x001a8>
> at CombatExtended.Verb_ShootCE.WarmupComplete () <0x002bf>
> at Verse.Stance_Warmup.Expire () <0x00022>
> at Verse.Stance_Busy.StanceTick () <0x0002b>
> at Verse.Stance_Warmup.StanceTick () <0x003bb>
> at Verse.Pawn_StanceTracker.StanceTrackerTick () <0x0005d>
> at (wrapper dynamic-method) Verse.Pawn.Tick_Patch1 (object) <0x00178>
> at Verse.TickList.Tick () <0x00487>

**Comment by skycrossercat** [comment]
Can you confirm the weapons you used are from which mod? Or they are CE's basic weapons? You can only confirm it is a CE:FT problem when the problem happens even only CE:FT and Core are loaded.
Sometimes some bad patches or mods have their unique C# based feature can break other mods.

**Comment by BValon** [comment]
I can throw another log with just Core and CE:FT loaded if needed, but yes, with just Core and CE:FT, the issue still occurs, with the base bolt-action rifle and revolver.

**Comment by skycrossercat** [comment]
I played rimworld with CE:FT and tons of other mods yesterday, didn't encounter any problem. But I didn't see any of basic weapons since I have a lot of weapon mods, maybe I can test it later.
Also, try test with original CE version by the same method to confirm the source of problem.

**Comment by BValon** [comment]
I just now tested it with regular CE and Hugs and it works as it should.

Reverted back to Hugs and CE:FT, the problem still occurs.

I can test with various weapons on my end and let you know, if that would help anything.

**Comment by sumghai** [comment]
The debug log suggests something screwy with the corresponding ammo and projectile defs used by those weapons - with did update our entire ammo library to 1.6/1.8+ standards, although I'd doubt that would be the cause.

In any case, please get back to use with the specific list of weapons affected by this issue - if you can get the actual defNames (not just the in-game player-readable labels), that would help us track the issue down faster.

Also, please make sure you are reproducing this issue on a brand new save with only Core and CE:FT (not just reloading an existing problematic save).

**Comment by sumghai** [comment]
One other thing - try getting rid of HugsLib too, just to be sure.

**Comment by skycrossercat** [comment]
@BValon I've test the issue with my heavy modded save (include CE:FT and HugsLib of course), no such problem nor log appeared. The bolt-action rifle and revoler fired correctly in my game, so maybe there's something go wrong with your game or mods.

**Comment by BValon** [comment]
I'm going through with testing now. All my tests are done with a new generated colony every single time using dev mode. 

Either way:

After clearing the configs and starting from scratch (disabling cloud saves as well), I'd like to point out that this menu pops up when first going into the settings for CE:FT.
https://i.imgur.com/vjkqBg7.png

Going into testing each weapon, I'm noticing a lot of weapons have the wrong models. My test pawn here is holding a M240B machine gun, and yet this model of something else.
https://i.imgur.com/KiyAo3c.png

I'll do more testing after I sleep, but I will keep you updated. So far though, the only two weapons that have been able to fire is Gun_ChargeRifle and Gun_AGSThirty.

**Comment by sumghai** [comment]
Those are rather bizarre errors.

* That warning message about enabling/disabling ammo should only appear when you actually change the ammo settings. This suggests a corrupted mod config file.

* As for multiple weapons having the wrong model and being unusable, it's starting to sound like a corrupted installation.

* Finally, I also noticed the unusual Reload icon - that only happens if the guns are not patched properly, and if that is happening to vanilla CE weapons (whose patches CE:FT directly brought over unmodified from CE), that definitely suggests a corrupted installation.

I suggest completely uninstalling CE:FT, delete the cached mod settings xml files for CE and CE:FT, then reinstall them with a fresh download from the GitHub releases page.

**Comment by BValon** [comment]
So I did as was suggested, clearing configs and tried it on its own, with it working. I then tried installing Hugslib, and I enabled AllYourBase and it did its thing with Verbose Logging on, and got this log with the revolver and sniper rifle: https://gist.github.com/940808c0058445d5eff37921b6796891

Also, I have a theory about the wrong weapon models: The AGSThirty and M240B were never meant to be handheld weapons, but mounted on a tripod.

**Comment by BValon** [comment]
I had another thought: The unusual reload icon may be from the fact that I have been doing my tests without having ammo turned on.

This is another log after clearing out configs and not touching the ammo settings for the mod. https://pastebin.com/xCw7fT0j

**Comment by skycrossercat** [comment]
>Also, I have a theory about the wrong weapon models: The AGSThirty and M240B were never meant to be handheld weapons, but mounted on a tripod. 
What do you mean? They are already mounted turrets in base CE.
I also encountered the wrong texture issue before, but it is a load order problem that messes everything up.
And plz don't post the full log, just give the logs there's possibly related to the issue (most of the time the logs are duplicated cause system keep trying to find the thing they want), using the dev mode's debug log and its 'trace medium' function to obtain single log.

**Comment by BValon** [comment]
To be honest, I'm just trying to throw stuff at the wall and see what sticks. I'm really trying to make this work, and figure out why I'm the only one having this issue.

I think I figured it out. I implemented AllYourBase (https://github.com/RimWorld-CCL-Reborn/AllYourBase) as a method to fix another problem mod. When just these two mods are loaded, AmmoBases.xml is touched by AllYourBase and changes some of the code. [Here is the Diffchecker](https://www.diffchecker.com/yXaYz4Pg), showing the changes before and after running Rimworld with AYB.

**Comment by sumghai** [comment]
So for every single test so far, you've always had All Your Base enabled?

And since it's modifying AmmoBases.xml, that's a huge no-no in my books, as projectile behavior is also affected.

I'd chalk this one down as a third-party mod issue, as I've never really heard of anyone running AYB with CE or CE:FT before.

Thoughts, @AthenaSulisMinerva?

**Comment by BValon** [comment]
If you run AYB even once with Verbose Logging enabled, the files in CE:FT are permanently changed unless you replace the missing bits of code. Everytime I added more mods to check stability, I always had AYB with Verbose on, to try and fix incompatibilities. That was my mistake.

**Comment by sumghai** [comment]
I see. That's pretty nasty, actually.

Since CE:FT's AmmoBases.xml is the exact same unmodified file from the original CE mod, I suspect this issue should also occur when you run both AYB and the original CE.

Can you confirm this?

**Comment by BValon** [comment]
I just ran the test myself and can confirm this. The only minor difference is a bit of code regarding Medieval (Line 56) also being removed from CE.

https://www.diffchecker.com/1U761Cn4

**Comment by sumghai** [comment]
Oh yes, I remember now - I *did* modify AmmoBases.xml in CE:FT to add a new Medieval ammo category (which the original CE mod doesn't have).

I'll let @AthenaSulisMinerva make the final decision, but looks like the problem lies with AYB, not CE or CE:FT.

**Comment by BValon** [comment]
I would absolutely agree. Thank you everyone for the help.

**Comment by AthenaSulisMinerva** [comment]
After reviewing this entire conversation, it is clear that AYB is interfering with CE's ammo and projectile base defs, in a way that CE:FT cannot compensate on our end.

I recommend the following course of action:

* @BValon - please notify the developer(s) of AYB regarding this incompatibility. Make sure that they understand that this affects both the original CE mod *and* the CE:FT fork.

* I will update the CE:FT ReadMe with a statement regarding the incompatibility with AYB.

* @sumghai - please update the description on Steam when we do our next release

I think we can consider this matter closed.
