### ISSUE TITLE
Simply More Melee patch needs update

### ISSUE THREAD

**Issue by rodriguegaspard** [AthenaSulisMinerva/CombatExtendedFastTrack#237]
RimWorld version : 1.0.2408
CE:FT version : 1.0.1.8-FT-012
OS : Ubuntu 18.04 64 bits

Hi, The Simply More Melee mod was updated recently and added new weapons that are not patched to work with CE. They have no damage as shown here : https://i.imgur.com/8j7cqZ7.png
The weapons affected by this are the Claymore, Pike, Scythe, Warclub, Dagger, Quarterstaff, Khopesh and Scimitar.

**Comment by AthenaSulisMinerva** [comment]
> CE:FT versions : Latest from Steam

As per the issue reporting guidelines, please specify the exact version number of CE:FT, regardless of whether it is a Githib or Steam download.

The version information can be found in the About.xml file inside the About subdirectory of the mod folder, or in the mod description in the in-game mod menu.

**Comment by rodriguegaspard** [comment]
Sorry about that, corrected it.

**Comment by AthenaSulisMinerva** [comment]
Fixed in #247
