### ISSUE TITLE
Transport Pod event spawns fully healed pawns.

### ISSUE THREAD

**Issue by Zaken187** [AthenaSulisMinerva/CombatExtendedFastTrack#24]
So for some reason, transport pods spawn pawns that are fully healed.

Having the individual mods doesn't cause the issue, but have both ZL and CEFT at the same time does.

**Comment by AthenaSulisMinerva** [comment]
CE:FT isn't much different from CE, other than adding some new compatibility patches and ammo types.

Does this issue also occur when Zombieland is used with the original Combat Extended mod?

**Comment by TheEventHorizon** [comment]
I think this was patched today by the zombieland devs. They just pushed an update on steam a few hours ago.

**Comment by Zaken187** [comment]
They patched the surgery thing, the drop pod thing is a whole other issue.
Its not as big of a deal as Surgeries flat out not working though..

**Comment by AthenaSulisMinerva** [comment]
> I've tried both versions and it happened. 

Just to confirm, this issue happens in both CE and CE:FT?

If so, then that's not really our problem, since CE:FT will just include whatever fixes the original CE gets in their public releases.

**Comment by Zaken187** [comment]
> > I've tried both versions and it happened.
> 
> Just to confirm, this issue happens in both CE and CE:FT?
> 
> If so, then that's not really our problem, since CE:FT will just include whatever fixes the original CE gets in their public releases.

Aint that a pain. Okay that, Ill see if the CE team can fix.
