### ISSUE TITLE
Insanly low melee damage against structures

### ISSUE THREAD

**Issue by Nutellaschmier** [AthenaSulisMinerva/CombatExtendedFastTrack#243]
Hey,

now I noticed in my latest playtrough that raiders attacking my base do insanly low damage against walls or structures. Bullets and rockets are fine, they destroy and damage absolutly everything they hit, but melee weapons to little to no damage. My guy with a longsowrd does 1-2 damage to a inscet hive (vanilla insect hive) and raiders attacking my walls with melee weapons and even riding animals doing damage and still they only destroy about 5 hp  with 1-3 attacks. I had 3 raiders attacking random wall fragments outside and they took about 8 ingame hours letting all my pawns sleep in peace just to destroy a single wooden wall. I also suffer from that, because I need about 12 ingame hours with 5 pawns to destroy a single insect hive.
And this cant be a "problem of the normal CE" as I always hear, because after hours of testing and switching mods, it appears that escpecially this problem does not occur in with the base CE Mod, also they dont keep dropping theire melee weapons, neither does the spike trap instantly kill everything, as I was told thats also base CE-Mod problem.

I only use mods that are clearly supported by CE Fast track.
Also, the latest Update for the base CE Mod was 17, Nov. 2019, or can you only find new updates on github?

Greetings,

Joel

**Comment by skycrossercat** [comment]
Hi Nutellaschmier,
About the low melee damage to buildings, I encountered that during my gameplay as well. I think the base CE team has fixed it, but CE:FT team missed the pull requests and didn't inherit them to their branch.
As for the trap instant kill, that's not fixed yet iirc. There's still an issue thread opened in the CE team to report this problem yesterday. You can test it with centipedes again to see if it got instant kill with 216 damage or not (I don't use spike traps).
If you want the latest update from the base CE team, you can try the Development branch, but things there are not released yet and may be unstable, use it at your own risk.
(the dropping weapon issue... are you using simple sidearm or you mess up your loadouts? I haven't encountered such issue so far)

**Comment by Nutellaschmier** [comment]
Yeah I use simple sidearms, they not dropping them, just switchint them. There is a patch for that and it worked at first, but now not anymore. Well since your one of the heading guys looking at CE Fast Track, may you tell them that the fix of the low melee damage is not tranfered to CE Fast Track yet? Because when using the CE Base mod I have hihg amounts of errors during missing patches een when copying them from CE Fast track, probaly half of the def folder is missing then. 
Should I open another thread that the low melee damage was fixed in CE Base and needs to be trasnfered or may you do that? You are probaly closer to the Development then a thread of my side.
Let me know if it will be transfered, and thanks for the answer.

Greetings,

Joel

**Comment by skycrossercat** [comment]
I am not a member of CE:FT team, just a guy help dealing with questions if I could. I already notice the missing repos and open an issue thread for that, should be fixed later.
One another thing is that never try to test the same save with CE and CE:FT at the same time, that won't help you find where the problem. Once you start with CE:FT, you can only stay at CE:FT, or the patches missing in base CE would mess everything up.

**Comment by AthenaSulisMinerva** [comment]
@Nutellaschmier - when reporting issues, please follow the issue reporting guidelines by providing the relevant game and mod version numbers. 

I'd also suggest keeping your reports as concise and to-the-point as possible - long essays are not necessary.

The fix for this issue is apparently sitting in the **_development_** branch of the original CE repo, but as I explained in #246, we'll wait until they are merged into their main _**master**_ branch before we import them over as well.
