### ISSUE TITLE
explosives impossible to craft with ammo disabled.

### ISSUE THREAD

**Issue by BakerBoyN** [AthenaSulisMinerva/CombatExtendedFastTrack#245]
Disabling ammo seems to remove FSX and Prometheum from the game entirely, I am unable to create IEDs, grenades, and other explosive weapons. 

Could we get the option to disable CE ammo but keep base game and other mods ammo (and their recipes) like mortar shells?

**Comment by AthenaSulisMinerva** [comment]
This is beyond the scope or capabilities of the CE:FT team.

I suggest you raise this question in the original CE repo instead, as any changes that they make to their _**master**_ branch based on your request will eventually be brought over to CE:FT.
