### ISSUE TITLE
Normal CE patches compatible?

### ISSUE THREAD

**Issue by NMJohns** [AthenaSulisMinerva/CombatExtendedFastTrack#25]
If I have a regular CE patch for something will that work with CE:FT? 

~~Also, any plans for patching Dinosauria, Megafauna, or Alpha Animals?~~

**Comment by AthenaSulisMinerva** [comment]
Yes, CE:FT will recognize old patches originally written for CE.

To request compatibility patches for third party mods, please start a new issue for each of the three mods.
