### ISSUE TITLE
Learning How to Patch

### ISSUE THREAD

**Issue by Javierkid** [AthenaSulisMinerva/CombatExtendedFastTrack#250]
Id like to learn how to patch specific mods for CEFT. How do I get started.

I notice there is a slight armor issue as it regards to the forsaken mod

![image](https://user-images.githubusercontent.com/39473379/72481053-47bfe780-37c7-11ea-89e1-5c07ce83a96e.png)

Comparing to other armors in the game which have those values at 11, 20, 25 etc i feel this is rather weak. How would i go about making changes to this.. Would editing the XML file for the Forsakens mod alone work?

**Comment by skycrossercat** [comment]
It's not too hard to make xml. patch for CE now, CE team do a lot of efforts to simplify the procedure. Just find the folder of CE:FT patches in Steam-->steamapps-->workshop-->content-->294100-->1865597143-->Patches, and use one of them as an example to learn how to patch stuff.
Even a normal gamer like me can do this, so this is not so difficult to start with.

P.S. Make comparisons between the Core patch of CE to make sure the stat doesn't go too far. There are spreadsheets you can use as references as well (https://github.com/NoImageAvailable/CombatExtended/wiki/Stat-&-Balance-sheets).

**Comment by sumghai** [comment]
At some point, I'll write up some definitive tutorials for [our own wiki](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/wiki), which will cover both the nitty gritty details on how to patch certain things and bigger-picture things like how to organize your patch files.

@skycrossercat - we also have [our own Stats and Balance sheets](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/wiki/Stats-and-Balance-Sheets), which are more complete than the official CE ones.

**Comment by AthenaSulisMinerva** [comment]
In the meantime, @Javierkid, if you feel you can't fix the issue yourself in a timely manner, you can submit an actual issue ticket requesting a bugfix for the patch.

**Comment by Javierkid** [comment]
Hello again. Sorry for this late reply but ive been under the weather lately..
Anyway i went through the instructions you provided and notice that the Forsaken patch was missing a few lines in comparison to other patches as it relates to armor.

Like the blut and sharp stat def was missing for each armor. After filling in the blanks with the correct def names.

![image](https://user-images.githubusercontent.com/39473379/72671459-7da7da80-3a18-11ea-930a-fb8cdb61689a.png)

Also didnt know the condition of armors affected the final value.

**Comment by skycrossercat** [comment]
It actually has the armor value, the 'base value' you set is 22mm, but the apparel itself is almost broken(only have 16% hp), this will significantly effect the final armor value of the apparel.

**Comment by Javierkid** [comment]
Oh really what I meant is the appareldef file didnt have the following
![image](https://user-images.githubusercontent.com/39473379/72673749-a9d55280-3a3c-11ea-9fdc-3da1e14a57eb.png)

**Above screenshot is the Original Code**

![image](https://user-images.githubusercontent.com/39473379/72673768-cbced500-3a3c-11ea-903e-362f0e47731b.png)

And now this one above is what I added.

The initial post the armor had .69 RHA at 53%

Now at 16% it has 3.52

**Comment by AthenaSulisMinerva** [comment]
@Javierkid, @skycrossercat, @sumghai - GitHub issues are intended for identifying and solving problems quickly, not a forum or chatroom for "lessons" on learning to patch.

If you want to suggest fixes, you can either submit a pull request, or summarize what specific lines we need to add/change.

Will setting `ArmorRating_Sharp` to 22 and `ArmorRating_Blunt` to 35 be enough to close this issue?

**Comment by Javierkid** [comment]
Yea its enough to close the issue and sorry about that
