### ISSUE TITLE
Built-in Alpha Animals patch doesn't correct armor values

### ISSUE THREAD

**Issue by mman0385** [AthenaSulisMinerva/CombatExtendedFastTrack#256]
The built-in patch for Alpha Animals doesn't appear to patch leather armor values. For example, Gallatross leather is still at 2.5 sharp, even though it seems like it should be 0.83 from looking at the files. I have CE FT after AA in the load order, but I've tried before as well with the same result.

**Comment by AthenaSulisMinerva** [comment]
As per the issue reporting guidelines, please edit your original post with the version information of your operating system, game and mod version numbers.

**Comment by AthenaSulisMinerva** [comment]
Closed due to lack of response and non-compliance with issue reporting guidelines.
