### ISSUE TITLE
Make RN backpacks usable with Tac Vests

### ISSUE THREAD

**Issue by onigamii** [AthenaSulisMinerva/CombatExtendedFastTrack#27]
Hi, i noticed that the RimmuNation backpacks can't be used with the Tactical Vests so i wrote a small patch and figured i should share it here.

```xml
`<li Class="PatchOperationReplace">
  <xpath>
    Defs/ThingDef[
    defName="RNApparel_Backpack_Civilian" or
    defName="RNApparel_Backpack_Military" or
    defName="RNApparel_Backpack_Tactical" or
    defName="RNApparel_Backpack_Tactical_Sling" or
    defName="RNApparel_Backpack_PegasusEliteOps"]/apparel/bodyPartGroups
  </xpath>
					
  <value>
    <bodyPartGroups>
      <li>Torso</li>
    </bodyPartGroups>
  </value>
</li>`

**Comment by AthenaSulisMinerva** [comment]
@sumghai - Can you take a look at this when you're free?

**Comment by sumghai** [comment]
@onigamii - I'm not sure if this falls under the purview of CE:FT.

Are the Tactical Vests from RN as well, or from vanilla?

**Comment by onigamii** [comment]
Tactical Vests are from CE

**Comment by sumghai** [comment]
@onigamii - please test the following dev version of CE:FT, and confirm that the desired behaviour has been implemented:

https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/archive/b5623da5a1dd3171e8e23d266420f7c7a283b99f.zip

**Comment by onigamii** [comment]
@sumghai Sorry for the delay it's working as intended.

**Comment by sumghai** [comment]
Okay, thanks! I'll wrap things up around here.
