### ISSUE TITLE
[O21] Halo Compatiblity Patch

### ISSUE THREAD

**Issue by Zero-Requiem22** [AthenaSulisMinerva/CombatExtendedFastTrack#274]
NOTE: This is for requesting patches for a *new* third-party mod that CE:FT hasn't supported yet; if you are requesting changes to patches for an *existing* mod, please submit a Bug Report instead.

## Basic Information
[O21] Halo

**Steam Workshop page:**
https://steamcommunity.com/sharedfiles/filedetails/?id=1939162033&searchtext=halo

## Detailed Information
**What content from the mod needs to be patched by CE:FT?:**
(Tick all the boxes that apply)

- [x] Ammunition (e.g. Shells)
- [x] Apparel, Armor (e.g. Helmets, Vests)
- [ ] Apparel, General (e.g. Clothes, Hats, Gasmasks)
- [ ] Apparel, Loadbearing (e.g. Backpacks, Harnesses)
- [x] Apparel, Shields (e.g. Viking Shield, Riot Shield)
- [x] Pawns, Alien Races (e.g. pawns that rely on the Humanoid Alien Races framework)
- [ ] Pawns, Animals/Monsters/Mechanoids
- [ ] Pawns, Humans
- [x] Pawns, Vehicles (e.g. Tanks, APCs, Drones)
- [x] Weapons, Melee (e.g. Knives, Swords, Clubs, Lightsabers)
- [x] Weapons, Ranged (e.g. Pistols, Rifles, Rocket Launchers)
- [ ] Weapons, Thrown (e.g. Grenades, C4 charges)
- [ ] Items/Resources (e.g. Meals, Medkits, Drugs)
- [ ] Other (please specify):

```
If the mod has feature(s) not covered by the categories above, briefly describe them here
```

**Are there existing CE versions of the mod or patches out there?:**
No there are no there other CE Patches

Thank You for all the Amazing work you guys do! This is my first request so if I'm missing anything let me know!

**Comment by Zero-Requiem22** [comment]
I closed this because I've realized that the Mod Author for this Mod is incredibly Toxic and there is another mod that adds the Halo races in development, which was the main reason why I was hoping to have this mod Patched.

**Comment by AthenaSulisMinerva** [comment]
You are welcome to (re)open or close this request at any time, for any reason

Just so you know, the CE:FT team does not play politics or favorites, and just because the original mod author has a "toxic" reputation in the community, that doesn't prevent us from working on patches for their mods (unless there is objective, technical evidence that the mod was designed in a way to actively obstruct CE patching)

**Comment by Zero-Requiem22** [comment]
Oh why ofc, Yeah sorry if I came off as rude or spiteful. I just believe that it would be better for all involved if the mod author that had an obvious love for not only their work but for their supporters as well, had their mod patched in into CE:FT. rather than someone who blocks and bans people for asking questions he considers "Dumb" or has stated his disdain for working on certain projects yet continued work on said project. However if you guys still end up patching the mod later down the line than go right ahead, You guys have every right to do what you want. I just don't want to be responsible for it lol

**Comment by NinjaSiren** [comment]
> Oh why ofc, Yeah sorry if I came off as rude or spiteful. I just believe that it would be better for all involved if the mod author that had an obvious love for not only their work but for their supporters as well, had their mod patched in into CE:FT. rather than someone who blocks and bans people for asking questions he considers "Dumb" or has stated his disdain for working on certain projects yet continued work on said project. However if you guys still end up patching the mod later down the line than go right ahead, You guys have every right to do what you want. I just don't want to be responsible for it being suggested lol

Same feeling, though this is from his Vehicle Framework mod for Rimworld Vehicle. I am the current developer of the Yes, Vehicles, Finally! I also feel the same, when I posted him the issues that the mod is having, he kinda replies somewhat rudely. I do not have a grudge on him, but I am pretty dissatisfied on how he replies back.
