### ISSUE TITLE
Core - 12x64 charged

### ISSUE THREAD

**Issue by CountRendor** [AthenaSulisMinerva/CombatExtendedFastTrack#275]
12x64 charged ammo (which drops from centipedes in huge quantities, approx. 3000 per 1 killed centipede) can be sold for 2$ per bullet. Profit - 6000 silver per killed centipede. I think this is too much

**Comment by AthenaSulisMinerva** [comment]
This is **not** a mod compatibility patch issue.

Please follow the proper issue reporting guidelines, and use the issue templates as given. Only CE:FT staff are permitted to deviate from issue guidelines and templates.

**Comment by NickZiggy** [comment]
Good luck with this one @CountRendor you will need it

**Comment by AthenaSulisMinerva** [comment]
Closing as OP has failed to follow up on the issue using the proper issue reporting guidelines.
