### ISSUE TITLE
Rabbie the Moonrabbit Mod

### ISSUE THREAD

**Issue by Inazuma00** [AthenaSulisMinerva/CombatExtendedFastTrack#28]
looks like they have similar weapon usage and stuff to Kurins, hoping it wouldnt be too hard
https://steamcommunity.com/sharedfiles/filedetails/?id=1837246563

~also about the issue before with no mechanoid raids, it seems it also affects factions with no sapper pawnkind and ImmediateattackSmart was disabled or somewhere around there. 
was recommended to delete \CombatExtended\Patches\Core\Storyteller\RaidStrategies.xml to restore the vanilla raid behaviour and avoid the error for now. NIA is currently working on it but idk when the patch will come out.~

**Comment by AthenaSulisMinerva** [comment]
Since @sumghai has too much on his plate right now, I'll look into this when I have the time.

Also, please don't discuss unrelated issues in the same topic.

**Comment by Inazuma00** [comment]
hello, it seems like someone made a CE patch for rabbie but it's incomplete, i hope this helps in easing up the work on it
https://steamcommunity.com/sharedfiles/filedetails/?id=1843574431&searchtext=

**Comment by AthenaSulisMinerva** [comment]
The CE:FT team will usually rewrite the patches from scratch ourselves.

@Inazuma00 - Please test our latest commit.

**Comment by AthenaSulisMinerva** [comment]
I've tested the patches myself with no problems, and since @Inazuma00 has not responded in a timely manner, I'm going call this one done.
