### ISSUE TITLE
Brain Injury Auto-Healing [CE Bug]

### ISSUE THREAD

**Issue by AuroraNovaem** [AthenaSulisMinerva/CombatExtendedFastTrack#284]
## Basic Information
**Operating System:** Win. 10 - 64b
**Physical Memory/RAM Capacity:** 64GB

**RimWorld Version:** 1.0.2408 rev747`
**CE FastTrack Version:** 1.0.1.8-FT-12 to FT-14
```

**Summary of Issue:**
Brain injuries of all types heal/heal at the same rate as a normal injury (eg. finger injury.)

## Detailed Information
**What is the expected/correct behavior?:**
Brain injury of any default type should result in immediate scarring

**What is the actual behavior?:**
Brain injury of any default types heals and gets infected at the same rate as a normal injury.

**Steps to reproduce the problem:**
Damaging head with any (low damaging) weapon or using development mode to apply any damage that results in brain injury under complete vanilla.
```
Assuming on how it was found out.
1. Loaded game under extreme mod list.
2. Played normally, and dealt with raid.
3. Landed extremely low damage weapon shot on raider, downing them.
4. Captured, and proceeded to observe raider's brain injury healing at the same rate as all other injuries 
5. Raider was originally assumed to be a comatose organ donor; 
6. Proceed with standard testing before coming to Core + CE:FT and determining error was on CE healing values.
```

**Screenshots:**
```
No screenshots, likely float error.
```

**Error Messages / Log Files:**
```
No direct errors as a result of it being a likely typo (eg. 0.1 instead of 0.01)
```

## Declarations of Due Diligence
- [ X ] (Tick) By submitting this bug report, I declare that:

* I have tested to make sure a new savegame works with only Core and CE:FT
* I have tested to make sure this issue is not also found in the original Combat Extended mod
* I have narrowed down the affected mod(s), by testing them individually or through a binary search
* I have searched the issue tracker, and made sure this issue hasn't been reported before
* I am reporting only one issue at a time, and not combining several issues in one report
* I understand that the CE:FT team reserves the right to close my issue at any time, regardless of whether or not my problem has been resolved, if I have been found to not have performed the due diligence required

```
This is likely a float typo in how damage is handled on the brain.
Since CE usually results in instant death under normal conditions this would be exceedingly hard to detect normally.

-------

## EDIT
**This actually seems to be related to all scar formation as opposed to just the brain, but I'll need to test this part more.**

**Comment by AthenaSulisMinerva** [comment]
CE:FT has not made any modifications to injury healing rates.

Were you able to reproduce this with the latest version of the original Combat Extended mod as well?

**Comment by AuroraNovaem** [comment]
Yes, This occurs on the latest available steam version, under current testing.

And to clarify, This does indeed seem to affect all scar formation but I can't say that for certain due to how semi-random scarring is for other body parts yet.

But even under horrid conditions, terrible healing, sleeping on floor, etc, all I've had occur are infections and then the wound heals as if nothing happened. No scarring at this time has occured.

I'd have edited this to be more concise, But photoshop is having errors. Sorry.

RAWS included
![VAN](https://user-images.githubusercontent.com/60705204/73927044-b102ba00-489e-11ea-8348-fb30b83f5cd6.jpg)
![VAN - BEFORE](https://user-images.githubusercontent.com/60705204/73927054-b3fdaa80-489e-11ea-95e1-f6a7e80bb977.jpg)
![VAN- AFTER](https://user-images.githubusercontent.com/60705204/73927074-b9f38b80-489e-11ea-805d-dc03892ae1e2.jpg)

CE
![CE](https://user-images.githubusercontent.com/60705204/73927226-fcb56380-489e-11ea-82f4-a5db38864e2d.jpg)
![CE Before](https://user-images.githubusercontent.com/60705204/73927231-fe7f2700-489e-11ea-85a0-b7da62b548d6.jpg)
![CE After 1](https://user-images.githubusercontent.com/60705204/73927238-0212ae00-489f-11ea-98ae-52f938388b4a.jpg)
![CE After Healing](https://user-images.githubusercontent.com/60705204/73927244-03dc7180-489f-11ea-9dab-baf5d620b8a6.jpg)

This applies all the same for Fast track as well.

**Comment by AthenaSulisMinerva** [comment]
If this issue also occurs in the original Combat Extended mod as well, then I suggest you submit this bug report to their issue tracker instead.
