### ISSUE TITLE
[Branch Request] Combat Extended - Lite

### ISSUE THREAD

**Issue by HappyHead** [AthenaSulisMinerva/CombatExtendedFastTrack#285]
A branch of CE which has the features for which patches need to be constantly made removed.
Basically, as many CE mechanics as possible but with Vanilla's damage and armor values.
Associated mechanics (like ammunition and melee parry/dodge chances varying by weapon) will obviously need be cut as well.

CE items for which mechanics must be cut (such as shields or CE unique guns) would be given vanilla values.

This would be a branch which, after launch, would need minimal maintenance unless mainline CE adds a new mechanic. Being absent of CE's more unique features, this would be a version of CE intended for people using mods which are unlikely to be patched into CE:FT, or are otherwise too impatient to wait for such a patch to be made.

**Comment by AthenaSulisMinerva** [comment]
This is completely outside the scope of CE:FT.

Also, this ticket was not submitted using one of the approved issue reporting templates.

Closing.
