### ISSUE TITLE
GUI/HUD unresponsive, bugged.

### ISSUE THREAD

**Issue by AnimatedTanker** [AthenaSulisMinerva/CombatExtendedFastTrack#290]
## Basic Information
**Operating System:** Windows-10 64 Op. System
**Physical Memory/RAM Capacity:** 8Gb RAM

**RimWorld Version:** 1.0.2408 rev748
**CE FastTrack Version:** 014 and below.
**Affected Mod(s) and Version(s): CE:FT Latest 
```
* Core
* CE:FT Latest Github
```

**Summary of Issue:**
Testings and conclusion of GUI or HUD problems that has been cropping up.

## Detailed Information
**What is the expected/correct behavior?:**
Long i used this i expected to work still fine.

**What is the actual behavior?:**
Sadly the HUD appears to be unresponsive compared to the last time i have used this. Even Standalone.

**Steps to reproduce the problem:**
```
The problem automatically produces upon select and startup of any scenario regardless of order or only being by itself.
```

**Screenshots:**
```

![image](https://user-images.githubusercontent.com/23154726/74155128-5cd33f00-4bea-11ea-9d0a-481cf43e99e3.png)

![image](https://user-images.githubusercontent.com/23154726/74155018-27c6ec80-4bea-11ea-80aa-af9d18cb67e2.png)

![image](https://user-images.githubusercontent.com/23154726/74191529-2a493680-4c2a-11ea-9a39-30e33ee9ef92.png)

```

**Error Messages / Log Files:**
```
RimWorld 1.0.2408 rev748
Verse.Log:Message(String, Boolean)
RimWorld.VersionControl:LogVersionNumber()
Verse.Root:CheckGlobalInit()
Verse.Root:Start()
Verse.Root_Entry:Start()

**Removed non-problematic logs**

Root level exception in OnGUI(): System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.MapInterface.MapInterfaceOnGUI_BeforeMainTabs () [0x00000] in <filename unknown>:0 
  at RimWorld.UIRoot_Play.UIRootOnGUI () [0x00000] in <filename unknown>:0 
  at Verse.Root.OnGUI () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String, Boolean)
Verse.Root:OnGUI()

*GUI Problem spammed 998 times, system automatically stopped logging at this point.*

Reached max messages limit. Stopping logging to avoid spam.
Verse.Log:Warning(String, Boolean)
Verse.Log:PostMessage()
Verse.Log:Error(String, Boolean)
Verse.Root:OnGUI()

```

## Declarations of Due Diligence
- [x] (Tick) By submitting this bug report, I declare that:

* I have tested to make sure a new savegame works with only Core and CE:FT
* I have tested to make sure this issue is not also found in the original Combat Extended mod
* I have narrowed down the affected mod(s), by testing them individually or through a binary search
* I have searched the issue tracker, and made sure this issue hasn't been reported before
* I am reporting only one issue at a time, and not combining several issues in one report
* I understand that the CE:FT team reserves the right to close my issue at any time, regardless of whether or not my problem has been resolved, if I have been found to not have performed the due diligence required

**Comment by AthenaSulisMinerva** [comment]
I'm having serious trouble understanding your grammar. So what you're saying is:

1) CE:FT worked fine in the past
2) You started experiencing GUI issues after an (unknown) CE:FT update

Is this correct?

If so, what was the _original_ version number of CE:FT that was working correctly for you?

> **Affected Mod(s) and Version(s): CE:FT Latest

We do not have a version number called "CE:FT Latest". Please report the correct version number as listed in the mod's about page in the game's mod selection screen.

**Comment by AnimatedTanker** [comment]
Sorry lots for the grammar, by latest i do mean Combat Extended: FastTrack Edition - v1.0.1.8-FT-014, but even also 013. And the GUI problem seems to persist regardless of load order. The version that was working for me was one of the 2019 between either August and November, i cannot remember which one specifically. Again, pardon for my wordings and/or grammar.

**Comment by AthenaSulisMinerva** [comment]
>  The version that was working for me was one of the 2019 between either August and November, i cannot remember which one specifically.

Please go find out which exact version number you were running _during this period_, so that we can narrow down what changes between that the and the current version (if any) may have caused this issue.

**Comment by AnimatedTanker** [comment]
The last version that worked well for me was Combat Extended: FastTrack Edition\nVersion: 1.0.1.5-FT-003 last in August 14, 2019 before having a new computer after christmas. I'm unknown what version of Rimworld was at that time, but i only managed to find the last date and version.

**Comment by meatball113** [comment]
Okay so I just started a new game and I'm on 1.0.1.8-FT-014 and I don't have any log spam, this is also with my entire modlist, 100+ mods.

Have you tried completely uninstalling rimworld from steam and redownloading? Maybe something is corrupt

**Comment by AnimatedTanker** [comment]
I have, yes. sadly to no avail, CEFT nor CE works on my end. With and without mods other than itself without Hughs or Jects, just being Core and CEFT 014

**Comment by AnimatedTanker** [comment]
Once again to confirm my report; I have verified and reinstalled Rimworld, loaded up Either CE or CEFT alone, still the same problem it spews out upon landing with the Map.Interface GUI, unable to click on the pawns, open tabs or open world. Man, i really love this mod and CEFT alot but it pains me that i have to settle on vanilla just because rimworld doesn't wanna cooperate with me. Saddened but hopes still high.

**Comment by Wuldahfel** [comment]
I had the exact same problem. If you're using the x32 version of the client, switch to the x64 one.

**Comment by AnimatedTanker** [comment]
This may sound dumb, but how do i know if it's x32 or x64 and how would i change it?

**Comment by rimpy-custom** [comment]
AnimatedTanker, give more information. The best you can do is to enable Core, HugsLib and CE:FT, then run game, replicate the issue and press Ctrl+F12. Send report to the internet and give link on it.

**Comment by AthenaSulisMinerva** [comment]
Perhaps after you changed to a new computer, you went back to running the 32-bit version of the game by accident?

To find out which version of the game you are currently running:
* Start the game
* Open up Task Manager with `Ctrl-Shift-Esc`
* Check the list of processes:
  * If you see RimWorldWin, you are running the 32-bit version
  * If you see RimWorldWin64, you are running the 64-bit version

To run RimWorld in 64-bit:
* If you have the non-Steam version, go to the RimWorld installation folder, find RimWorldWin64.exe and make a shortcut to it from the desktop
* (I have no idea what the instructions are for the Steam version, since I don't use Steam)

@rimpy-custom - We would prefer users NOT provide us with (entire) HugsLib logs, but instead just short snippets of the relevant in-game debug log, as the OP has already done.

**Comment by AnimatedTanker** [comment]
It appears my installation does not provide a 64bit, as it only provided me with 32bit. I do have a non-steam version. I am more confused at this because if incase before getting a new computer, my old one could have also not been 64bit and yet worked well with CEFT and alot of mods together. Now it just makes me wonder why this is happening even more. To a degree of not being provided with 64bit or not being worked. Again, i presume this entirety problem will eventually lead to nowhere but a dead end. Pardon me for wasting enough time. I'll continue to attempt to find a solution unless provided with one. I thank all that has attempted to help out lots and greatly appreciate it.

**Comment by AthenaSulisMinerva** [comment]
>It appears my installation does not provide a 64bit, as it only provided me with 32bit. I do have a non-steam version.

If you brought the non-Steam version, Tynan would have (automatically) emailed you a SendOwl download link. Search your email inbox, or [request a new download link from the official website](https://rimworldgame.com/getmygame/) using the email address you made your original purchase with:

![Capture_1](https://user-images.githubusercontent.com/49829079/74435271-03e00100-4e9f-11ea-8aa2-8a565d0754d3.png)

Then go to the SendOwl page and pick the 64-bit version of the game download:

![Capture_2](https://user-images.githubusercontent.com/49829079/74435324-26721a00-4e9f-11ea-854f-77cd323decf5.png)

>I am more confused at this because if incase before getting a new computer, my old one could have also not been 64bit and yet worked well with CEFT and alot of mods together. 

Looking at your older comments, you last used 1.0.1.5-FT-003 successfully on a 32-bit version of the game, because at that time FT-003 had far less content than FT-014.

Between FT-003 and the current FT-014 update, both CE and CE:FT had major updates, which is why you need to now run RimWorld 64-bit instead in order to use either mod.

**Comment by AnimatedTanker** [comment]
I would like to apologize for this thread. It appears you were right albeit i had to use the steam version as that has fixed my problem through various support. It seems my installation refused for some unknown reason to not applicate 64 bit version.

**Comment by AnimatedTanker** [comment]
Everything now works fine as it is. I presume faulty program on my end with alot of patience. ^^' cheers and pardon again for this discussion i shall close it to disclose further post.
