### ISSUE TITLE
Chicken Plucker's Rimmu-Nation & Red Horse Mods

### ISSUE THREAD

**Issue by sumghai** [AthenaSulisMinerva/CombatExtendedFastTrack#3]
Just making a TODO list for myself and @Freedom187 - thanks for hosting our patches, Athena!

- [x] Red Horse Furniture
- [x] Rimmu-Nation Clothing
- [x] Rimmu-Nation Weapons
- [x] [RH] Umbra Company
- [x] [RH] The Ghosts
- [x] [RH] Militaires Sans Frontieres ~~(just missing non-lethal ammo textures)~~ (textures done!)
- [x] [RH] Task Force 141
- [x] [RH] Last Man Mercs
- [x] [RH] Elite Crew
- [x] T-45b Power Armor

**Comment by sumghai** [comment]
Okay, we're done here!

@AthenaSulisMinerva - Please update the supported mod list in the README with all the RN mods.

**Comment by AthenaSulisMinerva** [comment]
Done. Thanks for your patches.

**Comment by sumghai** [comment]
Reopening due to bug report on Ludeon Forums, regarding the T-55 tanks from LMM being easily killed by small arms fire (instead of being impervious like Mechanoids).

**Comment by sumghai** [comment]
Okay, just pushed a hacky workaround to make LMM faction T-55 tanks impervious to small arms fire, but still vulnerable to grenade or rocket launchers.

**Comment by sumghai** [comment]
I finally implemented proper patches for the LMM faction tanks, which correctly defines armor coverage so that I no longer need the hacky workaround from d3cf28d.

Also, the original user who initially reported the bug on the Ludeon Forums has indicated he is happy with the latest patches, so we're done here for realsies.
