### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by michaelmuir00** [AthenaSulisMinerva/CombatExtendedFastTrack#302]
Not an issue just a question of when we can expect a 1.1 compatibility patch or release? 

Still a big fan of CE:FT

**Comment by AthenaSulisMinerva** [comment]
As per the announcement on Steam Workshop, CE:FT is merging with CE.

Therefore, CE:FT will **not** be updated to 1.1, and this issue tracker will be closed by 1 March 2020.
