### ISSUE TITLE
XML error using CE:FT

### ISSUE THREAD

**Issue by ManiacDK** [AthenaSulisMinerva/CombatExtendedFastTrack#35]
So i recently switched from the regular and its extensions to CE:FT, and now when I start the game up I get a lot of errors about and I quote.
" XML error: Duplicate XML node name MeleeParryChance in this XML block: <statBases><MoveSpeed>3.35</MoveSpeed><ComfyTemperatureMin>-16</ComfyTemperatureMin><MarketValue>225</MarketValue><MeleeDodgeChance>0.17</MeleeDodgeChance><MeleeCritChance>0.1</MeleeCritChance><MeleeParryChance>0.05</MeleeParryChance><MeleeDodgeChance>0.17</MeleeDodgeChance><MeleeCritChance>0.1</MeleeCritChance><MeleeParryChance>0.05</MeleeParryChance></statBases>" This is just a short cutout of the entire list it prints for me to look at, with small variations.
There is also a variation called MeleeCritChance and MeleeDodgeChance.
Is there any way to fix this?
If you need more need please tell me what to provide.
Thanks in advance :)
Also apologies for posting stuff not related to the first issue I had.

**Comment by AthenaSulisMinerva** [comment]
What mods are you using?

To diagnose the problem:
- Start a new, separate savegame with only CE:FT enabled
- Confirm that the issue does not appear (yet)
- Add your other mods one at a time until you get the same error message

Only then will we be able to know which mod is causing the problem.

**Comment by ManiacDK** [comment]
I am running:
Mod - e
Core
Mod Manager
Miscellaneous 'CORE'
HugsLib
Giddy-up! Core
Vanilla Furniture Expanded & Vanilla Furniture Expanded - Medical
RimStory
Show Draftees Weapon
Recipe icons
Combat Extended Fast Track
Combat extended Shields
Combat extended Guns
Roof support 1.0
RimHUD
What the hack?!
Psychology
Medical Tab
Relations Tab
Colony Manager
Outdoor Lighting
MineItAll - 1.0
ED-EnhancedOptions
[RF] Tribal Pawn Names [1.0]
Giddy-up! Mechanoids
AnimalCollabProj
Hardworking animals 1.0
Hospitality
A Dog Said... Animal Prosthetics
AnimalCollabProj Patch Pack
Bullet Casings
Metalic batteries
Scar removal
Foxes Aren't Suicidal
Interaction Bubbles
Children, school and learning
Animal Variety Coats
Blueprints
While You're Up [1.0]
More Slaves [1.0]
More Harvest Designators!
Reasonable Components V1
Where's the gravel?
Deep Ore Identifier
Room Sense
Smart Medicine
Shield Generators
RunAndGun
Gear Up And Go
ResearchPal
QualitySurgeon
Realistic Rooms
Allow Tool
Concrete Walls
Floored
Glass+Lights
Conduit Deconstruct
Damage Indicators
Apparello 2
advanced powergeneration v1
Advanced Shield Belts
Incident Person Stat
Ancient Structures
Centralized Climate Control
Better Workbench Management
Better Pawn Control
Animal Food Restrictions
BioReactor
Electric Stonecutting Table
SF Rain Removes All Filth
[FSF] Indoor Tree Farms
[FSF] No Default Shelf Storage
[KV] mod; All KV mods
Simple sidearms
QualityBuilder
RT Solar Flare Shield
Misc. Robots
Misc. Robots++
More Trade Ships
Door Mat R1.0
Color Coded Mood Bar
EdB Prepare Carefolly
Expanded Prosthetics and Organ Engineering
VGP Garden drinks
VGP Garden fabrics
VGP Garden medicine
VGP Garden Resources
VGP Garden Tools
BGP more veggies
VGP Soylent production
VGP Vegetable Garden
VGP Xtra Trees and Flowers
Progress Renderer
Trading spot 1.0
Stack XXL
Save storage, outfit, crafting drug of operation settings 1.0
Real ruins
RT fuse
Stockpile stack limit
Defensive machine gun turret pack
defensive positions
ETRT: industrial tweaks
Faction discovery
Faction Task Force 141
Guards for me
Mad skills
mercenaries for me
Misc Training
More Trait slots 1.0
Path avoid 1.0
Pick up and haul
Questionable Ethics Enhanced
Red horse furniture
Rimfridge 1.0
Rimmu-nation clothing
rimmu_nation weapons

 
It appears to be the AnimalCobbalProj Patch Pack in my load order that causes this issue.

**Comment by AthenaSulisMinerva** [comment]
Remove the AnimalCollabProj patch pack - CE:FT already comes with built-in support for AnimalCollabProj.

For a full list of mods CE:FT already supports, please refer to the [README](https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/blob/master/README.md).

**Comment by ManiacDK** [comment]
Thanks for helping me.
As a seperate question retaining to my mod list, should I remove any other mods to avoid something similar from happening?
Also apologies for being a bit of an idiot and not reading the readme, or the description of the mods I am using.

**Comment by AthenaSulisMinerva** [comment]
Once again, please refer to the README for the list of mods with built-in support.

Since this issue has been resolved, I'm going to close it now.
