### ISSUE TITLE
Incompatible with Doors expanded?

### ISSUE THREAD

**Issue by Kazzerk** [AthenaSulisMinerva/CombatExtendedFastTrack#36]
I have lag spikes with explosions with this mod and Doors Expanded.

You can read from the last update "Fixes explosion slowdowns that occur while playing the CE mod coupled with Doors Expanded. The fix was engineered by JonnyNova."  I think the fix doesn't work for CE:FT. I removed Doors Expanded and my problem with explosions was gone

Log doesn't show any error when this happen.

Doors Expanded [Ludeon ](https://ludeon.com/forums/index.php?topic=39264.120) [Workshop ](https://steamcommunity.com/sharedfiles/filedetails/?id=1316188771&searchtext=doors)

**Comment by AthenaSulisMinerva** [comment]
CE:FT still uses the same assembly name and class references as the original CE mod, so the fixes from Doors Expanded that apply to CE should also automatically work for CE:FT.

Can you try starting a new save game with **_only_** CE:FT and Doors Expanded, just to confirm that it's not a third-party mod that's actually causing problems?

**Comment by AthenaSulisMinerva** [comment]
@Kazzerk, can you please follow up on my last request? Otherwise, I will have to close this issue.

**Comment by AthenaSulisMinerva** [comment]
Closed due to no response or follow-up.
