### ISSUE TITLE
[Combat Extended] Patch operation Verse.PatchOperationFindMod(Glitter Tech, Glitter Tech (No Surgery)) failed

### ISSUE THREAD

**Issue by Taranchuk** [AthenaSulisMinerva/CombatExtendedFastTrack#37]
Error message:
```
[Combat Extended] Patch operation Verse.PatchOperationFindMod(Glitter Tech, Glitter Tech (No Surgery)) failed
file: D:\GAMES\RimWorld1-0-2282Win64\Mods\Combat Extended\Patches\Glitter Tech\GlitterTech_CE_Patch_TraderKinds.xml
Verse.Log:Error(String, Boolean)
Verse.PatchOperation:Complete(String)
Verse.LoadedModManager:ClearCachedPatches()
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.Root:<Start>m__1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__1()
```
When I load the original CE, then there is no error. There is an error in the Fast Trask master. Hugslib log: https://gist.github.com/HugsLibRecordKeeper/22cdab2be3f0c5a1df032f314be61ebc

**Comment by Taranchuk** [comment]
I got rid of the error by inserting the line <success>Always</success> below <match Class="PatchOperationSequence"> in the file GlitterTech_CE_Patch_TraderKinds.xml.

**Comment by sumghai** [comment]
Oh, shit!

@AthenaSulisMinerva - could you please hold off on publishing the next update? I gotta fix this first.

**Comment by AthenaSulisMinerva** [comment]
@sumghai - No worries. I'm also waiting on @Freedom187 to sort out the Steam Workshop ID file anyway.

**Comment by sumghai** [comment]
@Taranchuk - Please check my latest commit, and confirm that the issue has been fixed on your end as well.

**Comment by Taranchuk** [comment]
@sumghai the error is gone.

**Comment by sumghai** [comment]
@Taranchuk - Thanks!

@AthenaSulisMinerva - I'm marking this one as fixed.
