### ISSUE TITLE
Megafauna mod

### ISSUE THREAD

**Issue by NMJohns** [AthenaSulisMinerva/CombatExtendedFastTrack#38]
There's an already existing patch

Mod: https://steamcommunity.com/workshop/filedetails/?id=1055485938
Patch: https://steamcommunity.com/sharedfiles/filedetails/?id=1092233785

**Comment by AthenaSulisMinerva** [comment]
The CE:FT team will usually rewrite the patches from scratch ourselves.

**Comment by AthenaSulisMinerva** [comment]
@NMJohns, try the patches I just pushed to the repo and tell me if there are any problems.

**Comment by NMJohns** [comment]
I would love to. How would I add this to the Steam version? If I dropped the patches folder into my mods folder would it work?

**Comment by AthenaSulisMinerva** [comment]
Put the patches inside the **`[Steam Workshop Folder for CE:FT]\Patches\Megafauna\`** directory.

**Comment by AthenaSulisMinerva** [comment]
@NMJohns, have you tested the patches yet?

**Comment by NMJohns** [comment]
Will test today.

**Comment by sumghai** [comment]
Hey @AthenaSulisMinerva, I've tested your Megafauna patches and they work just fine.

**Comment by AthenaSulisMinerva** [comment]
Thanks @sumghai - that's good enough for me, so this is done.
