### ISSUE TITLE
NewRatkinPlus mod

### ISSUE THREAD

**Issue by AthenaSulisMinerva** [AthenaSulisMinerva/CombatExtendedFastTrack#39]
Original mod: https://steamcommunity.com/sharedfiles/filedetails/?id=1578693166

**Comment by N7Huntsman** [comment]
Patch already exists, and is in the process of being integrated into CE. https://steamcommunity.com/sharedfiles/filedetails/?id=1739122102

**Comment by AthenaSulisMinerva** [comment]
sumghai gave me a copy of your Steam patch, and although I'm adopting most of the apparel and weapons values you've defined, I'll be handling pawn magazine count and crossbolt ammo differently.

Your current patch is also not compatible with a couple of new Ratkin features.

**Comment by AthenaSulisMinerva** [comment]
Accidentally forgot to uncomment a line in the weapons patch file.
