### ISSUE TITLE
Firing over the shoulder

### ISSUE THREAD

**Issue by Nanao-kun** [AthenaSulisMinerva/CombatExtendedFastTrack#40]
Vanilla Rimworld allows pawns to fire over the shoulders of a pawn in front of them. Doing the same in CE pretty much guarantees friendly fire. Was this feature intentionally disabled, or is it a bug? They can even easily hit downed pawns in front of them instead of the target.

**Comment by LockdownX7** [comment]
That's a bug, will be fixed in the next release.
