### ISSUE TITLE
A way to completely remove ammo?

### ISSUE THREAD

**Issue by Rancra** [AthenaSulisMinerva/CombatExtendedFastTrack#41]
Would it be possible to add an option to completely remove ammo from the game? It makes getting quest specific items like resurrector mech serum hard.

**Comment by AthenaSulisMinerva** [comment]
Both the original CE and the CE:FT fork have the option in the Mod Settings dialog to enable/disable ammunition:

![Untitled](https://user-images.githubusercontent.com/49829079/65423110-d84e7280-de3a-11e9-8f76-b2b097342f19.png)

Does that not work for you?

**Comment by Rancra** [comment]
After making a new save im not having any more issues, thank you for the help.
