### ISSUE TITLE
Kijins race

### ISSUE THREAD

**Issue by raith7062** [AthenaSulisMinerva/CombatExtendedFastTrack#45]
https://steamcommunity.com/sharedfiles/filedetails/?id=1730054284&searchtext=kijin

link to the original mod.

**Comment by AthenaSulisMinerva** [comment]
The author ssulunge made [an attempt at CE patches](https://steamcommunity.com/sharedfiles/filedetails/?id=1768010561), although they couldn't do weapons and items for various reasons.

@sumghai - I just saw that you had contacted the author in the past. How did it go?

**Comment by raith7062** [comment]
Went pretty well actually. He's not hard to contact from my experience

**Comment by sumghai** [comment]
Yikes, I forgot to follow up on this. I'll do it when I have a bit more free time.

**Comment by sumghai** [comment]
Looks like Kijins mod support is coming soon from the upstream CE repo, so we'll fold that in when it drops.

**Comment by AthenaSulisMinerva** [comment]
Just found out that this original version of the Kijins mod has been declared obsolete by its author, so I'd imagine the CE and/or the CE:FT team will have to start from scratch.

#181 is the request for the 2.0 version of the mod.
