### ISSUE TITLE
Include attribution for patches

### ISSUE THREAD

**Issue by sumghai** [AthenaSulisMinerva/CombatExtendedFastTrack#5]
It would be nice if each of the supported patches in the README had the names of their authors.

**Comment by AthenaSulisMinerva** [comment]
Fair enough. This should be easy.

**Comment by AthenaSulisMinerva** [comment]
I put the names of the patch authors next to their mods in the list, but it makes the README file look bloated and harder to read to find out which mods are supported by CE or FastTrack. Many patches have more than one author, which makes the list look too wide.

![screenshot](https://user-images.githubusercontent.com/49829079/60192265-2bc71980-9868-11e9-81fc-adc61dd27a28.png)

If you don't mind, I think we should go back to the way it was before.

**Comment by AthenaSulisMinerva** [comment]
It will be easier to just have a simple list of names in a different part of the readme, maybe even just the ones who did the new patches in FastTrack.

**Comment by sumghai** [comment]
Yeah, in hindsight that makes sense - your screenshot definitely proves how cluttered my original idea was.

Thanks!
