### ISSUE TITLE
Zombieland targeting through walls

### ISSUE THREAD

**Issue by Nanao-kun** [AthenaSulisMinerva/CombatExtendedFastTrack#51]
Is there anyway to prevent pawns from trying to target zombies over walls?

**Comment by AthenaSulisMinerva** [comment]
Is this an issue specific to CE:FT, or does it happen in the original CE mod as well?

**Comment by Nanao-kun** [comment]
Checking with just Zombieland, Hugslib, and CE:FT, they do target. It also occurs with the original CE mod. It's odd though, as it's only some of the time. Perhaps some oddity with how the zombies target?

**Comment by AthenaSulisMinerva** [comment]
> It also occurs with the original CE mod.

As this is an issue with the original CE mod, your should ask about this issue over in their repo instead.
