### ISSUE TITLE
Medkits doon't work whenever i have this mod enabled.

### ISSUE THREAD

**Issue by Dayvox** [AthenaSulisMinerva/CombatExtendedFastTrack#58]
I like this mod and all, it's useful for combat extended but, every time I have it enabled medkits don't work, and this issue only happens when I have this specific mod enabled, it might have to do with other mods but I don't know.

**Comment by AthenaSulisMinerva** [comment]
* You need to be more specific by "not working". Do the medkits not spawn at all? Or do the medkits return error messages when pawns try to use them? (If so, please copy and paste the relevant error message).

* Do you still get this error when _only_ running Core and CE:FT?

* Do you get this error with the original CE mod?

**Comment by Dayvox** [comment]
> * You need to be more specific by "not working". Do the medkits not spawn at all? Or do the medkits return error messages when pawns try to use them? (If so, please copy and paste the relevant error message).
> * Do you still get this error when _only_ running Core and CE:FT?
> * Do you get this error with the original CE mod?

1. You can craft it, you start in the game with it, you can spawn it in dev mode, what's not working is that whenever a pawn tries to use it on another, it doesn't patch the wound, and the pawn tries repeatedly with other medkits to patch the wound when he ends all the medkits, he just seeks another to try to tend the pawn. And no error messages are shown, I've checked debug log various times and nothing

2. No, I also thought it would be an issue from a different mod, but I doubt since the only medical-related mods I have is the EPOE one and CONN.

3. I don't get this problem with the original CE mod
