### ISSUE TITLE
Cross Reference Errors

### ISSUE THREAD

**Issue by Necrikus** [AthenaSulisMinerva/CombatExtendedFastTrack#63]
I'm not sure what's triggering it other than CE, but I am getting errors on the main menu just from having it active. It seems that turrets are involved, but I'm not that good at reading the debug log to know much more than that. I just know that after removing numerous other mods, the errors went away after removing CE. 

https://gist.github.com/5d7dabefd4138883fe084d48975518e0

**Comment by AthenaSulisMinerva** [comment]
Try starting a new savegame with only Core and CE:FT - confirm that you don't get any errors with this configuration.

Then slowly add your other mods back in until you encounter your first error. That will give you a good idea of which mod is actually causing the problem.

**Comment by Necrikus** [comment]
I found the problem mod. It's the Trading Economy mod. Even after removing every mod but CE,  Trading Economy, and the mods that it requires I got the same errors. Not sure why that mod is causing issues when it's listed as being supported by CE.
