### ISSUE TITLE
Rimworld of Magic - Load Order

### ISSUE THREAD

**Issue by TheKaiser223** [AthenaSulisMinerva/CombatExtendedFastTrack#64]
Before or after "combat extended"? This must be such a stupid question and I don't know where to ask it, but no matter which order I put it in it's throwing up a bunch of errors, so I imagine I must be doing something wrong.

**Comment by AthenaSulisMinerva** [comment]
Load order should not matter.

Try start a new savegame with only the following:
* Core
* CE:FT <--- this can go anywhere after Core
* HugsLib
* Jecstools
* A RimWorld of Magic

Once you confirm you don't get any errors with this minimal setup, slowly add your other mods back in until you find out what is actually causing the error.

**Comment by TheKaiser223** [comment]
This can be locked, I overlooked something stupid. Sorry for wasting your time.
