### ISSUE TITLE
Loadout button gone?

### ISSUE THREAD

**Issue by Bruceuu** [AthenaSulisMinerva/CombatExtendedFastTrack#66]
My loadout button is gone. is this from an incompatibility
![gone](https://user-images.githubusercontent.com/46940139/65818972-2e466000-e217-11e9-8487-de48d0b6b473.png)

https://gist.github.com/26e9abe22285d517e7e6c4b03d5eb35e

**Comment by LockdownX7** [comment]
Likely a conflict with whichever mod is adding that Rules section. You're missing not only CE's loadout section, but also vanilla's food policies.

**Comment by AthenaSulisMinerva** [comment]
As usual:

- Start a new savegame with only Core and CE:FT loaded
- Confirm that having only those two mods does not cause any errors
- Slowly add and test your other mods back in **one by one** until you encounter this exact error

The last mod you added should be the one that has compatibility issues. Please report back once you have finished.

**Comment by AthenaSulisMinerva** [comment]
Closing due to no response.
