### ISSUE TITLE
Red Errors with Compatible Mods

### ISSUE THREAD

**Issue by Caferino** [AthenaSulisMinerva/CombatExtendedFastTrack#67]
https://gist.github.com/HugsLibRecordKeeper/460aba726c4bd66f95c105fdaca0f1a2

None of the mods in my list seem to be incompatible or leave a clue of causing a conflict, I already tried by disabling many of them and managed to solve tons of red errors I had before, but right now I struggle mainly with these two:

1. When choosing Rimcities's Friendly City scenario and then right after opening Prepare Carefully's menu, a red error pops up that says "Advanced Helmet not made from stuff: Pasteel, setting to null..." When the game begins, then another 2 join, regarding Flak Vest and another piece of vanilla armor set from null to default, it's odd, though not game-breaking.

2. Seems to be regarding A Rimworld of Magic, I get flooded with errors regarding PsionicHD something, stuff about casting abilities exceptions, jobs for combat, etc. I mainly focused on the Friendly City scenario, nothing else.

Also, I have other issues that might be completely unrelated to CE and maybe caused by FPS loss or game lag that the Combat Effects for CE mod adds, not sure, but in heavy fights or while using debug/god mode, the bottom menu sometimes disappears and the tiny black text boxes freeze in their place. This might be due to performance, but adding just in case.

Mod List in Order with Official Compatible mods in **Bold** and ~~Crossed~~:
~~**Startup Impact
BetterLoading
Core
HugsLib
Combat Extended: FasTrack Edition**~~
Combat Effects for CE
~~**Combat Extended Guns
JecsTool**~~
~~**A Rimworld of Magic
Giddy-Up Core
Giddy-Up Caravan
Giddy-Up Battle Mounts
Giddy-Up Ride and Roll
Vanilla Animals Expanded
Vanilla Animals Expanded CE Patch
Sparkling Worlds
Sparkling Worlds CE Patch
Humanoid Alien Races Framework
XenoHumans**~~
EDB Prepare Carefully
RimCities
Real Ruins
~~**Achtung!
Allow Tool**~~
Pick Up and Haul
Common Sense
~~**RIMMU Nation Clothing
RIMMU Nation Weapons**~~
Loot Boxes
~~**Expanded Prosthetics
Rah's Prosthetics
SRTS Expanded**~~
Ogre Stack
More Traits Slots
~~**Colorful Traits
Detailed Body Textures
Chicken Mitchell hair mod
gloomy_hair
Spoons Hair Mod
Xeva's Rimhair**~~
~~**Aparello 2
FashionRIMsta
Real Fog of War
Camera+
Damage Indicators
Realistic Planets
Realistic Darkness 1.0
RimHUD
Dubs Mint Menu
Relations Tab
RunandGun
Simple Sidearms**~~
War Crimes Expanded
~~**Verge of Galaxy (music mod)
P-Music
No Oxygen Included OST (music)**~~
Rimsenal - Storytellers
Simple FX - Smoke
Soil Contrast
Realistic Human Sounds
~~**RimSaves
Mod Manager**~~

Also... is CE:FT compatible with RJW?

Edit: Grammar & Crossed Startup Impact and BetterLoading mods because I do not think they should conflict with anything imo.

**Comment by AthenaSulisMinerva** [comment]
In the future, I would prefer that you post each problem in a separate issue, as lumping them all together makes them extremely hard to deal with.

> When choosing Rimcities's Friendly City scenario and then right after opening Prepare Carefully's menu, a red error pops up that says "Advanced Helmet not made from stuff: Pasteel, setting to null..." When the game begins, then another 2 join, regarding Flak Vest and another piece of vanilla armor set from null to default, it's odd, though not game-breaking.

Those problems are on Rimcities' end, not CE:FT. The author misspelled Plasteel, and did not explicitly define the `stuff` used to make the armors to be spawned in the scenario.

> Seems to be regarding A Rimworld of Magic, I get flooded with errors regarding PsionicHD something, stuff about casting abilities exceptions, jobs for combat, etc. I mainly focused on the Friendly City scenario, nothing else.

Try starting a new temporary savegame with only Core, CE:FT and A Rimworld of Magic (plus the absolute bare minimum of dependencies that RoM needs to work). If you don't see the error, then the mod conflict has nothing to do with CE:FT.

> Also, I have other issues that might be completely unrelated to CE and maybe caused by FPS loss or game lag that the Combat Effects for CE mod adds, not sure, but in heavy fights or while using debug/god mode, the bottom menu sometimes disappears and the tiny black text boxes freeze in their place. This might be due to performance, but adding just in case.

Does this also happen with the original CE mod?

> Also... is CE:FT compatible with RJW?

If a mod isn't explicitly listed in our README as being compatible, assume that it isn't compatible and use with extreme caution.

**Comment by AthenaSulisMinerva** [comment]
Closed as user did not respond.
