### ISSUE TITLE
Kurin Mod

### ISSUE THREAD

**Issue by sumghai** [AthenaSulisMinerva/CombatExtendedFastTrack#7]
Fixes and adjustments to patches originally written by @Togoasl 

TODO:
- [x] Allow Kurin to wear any item (not just Kurin-specific apparel)
- [x] Add backpacks to Kurin pawns
- [x] Patch Kurin apparel, armor ~~and weapons~~
- [x] Add ammo to Kurin starting scenario

**Comment by sumghai** [comment]
New Kurin patches confirmed working. We're done here.

**Comment by AthenaSulisMinerva** [comment]
Do you want me to add this to the mods list?

**Comment by sumghai** [comment]
Might be best to wait until I finish patching Rimworld of Magic, Forsakens and Kurin as well, so that you can make the edits in one go.
