### ISSUE TITLE
RN Weapons - incorrect SMG calibers (B&T MP9 and PP-19 Bizon)

### ISSUE THREAD

**Issue by kazenokizu** [AthenaSulisMinerva/CombatExtendedFastTrack#71]
The mp9 is in the wrong caliber and there are a few other weapons in the wrong caliber as well

**Comment by kazenokizu** [comment]
capacity if wrong would also be more cooler to have in 9x18 than 9x19  if possible both Feed system:
64-round helical magazine (9×18mm Makarov), 53-round helical magazine (9×19mm Parabellum) (Bizon-2-01)

**Comment by sumghai** [comment]
> The mp9 is in the wrong caliber

You're quite right - the Brugger & Thomet MP9 should be chambered in 9x19mm Parabellum.

I had specified the correct ammo in my stat spreadsheet, but for some reason the definition for .380 ACP got snuck in somehow.

> capacity if wrong

Assuming you were meant to say "capacity _is_ wrong", I'll note that the real-life MP9 can in fact accept 30-round box magazine.

> would also be more cooler to have in 9x18 than 9x19 if possible both Feed system:
64-round helical magazine (9×18mm Makarov), 53-round helical magazine (9×19mm Parabellum) (Bizon-2-01)

That is a horrible run-on sentence.

Yes, the PP-19 Bizon should be chambered in 9x17mm Makarov. No, CE and CE:FT isn't really design for AmmoSets that mix calibers, nor is it possible to have two or more different magazine sizes depending on caliber.

**Comment by sumghai** [comment]
This is now fixed.

**Comment by kazenokizu** [comment]
i did not say that the mp9 was the wrong capacity i was saying that the pp-19 bizon was based off the caliber and it is 9x18 makorov not 9x17   9x17 is 380 acp and is not the same thing

**Comment by sumghai** [comment]
Your sentences lack punctuation, so I don't really understand what you're trying to say at all.

**Comment by kazenokizu** [comment]
Ok lets try this one more time. The PP-19, has the wrong magazine capacity for the 9x19 cartridge.  So please fix it. to either be 9x18 64 rounds or 53 rounds for 9x19. 
The MP9, is in the wrong caliber please make it 9x19.

**Comment by kazenokizu** [comment]
好，讓我們再嘗試一次。 PP-19的9x19墨盒的紙匣容量錯誤。 因此，請修復它。 可以是9x18 64輪，也可以是53x 9x19。
MP9的口徑錯誤，請將其設為9x19。

**Comment by kazenokizu** [comment]
Hǎo, ràng wǒmen zài chángshì yīcì. PP-19 de 9x19 mòhé de zhǐ xiá róngliàng cuòwù. Yīncǐ, qǐng xiūfù tā. Kěyǐ shì 9x18 64 lún, yě kěyǐ shì 53x 9x19.
MP9 de kǒujìng cuòwù, qǐng jiāng qí shè wèi 9x19.

**Comment by sumghai** [comment]
Oh, so your native language is Mandarin.

As per commit b575bc5, I've already fixed the patches as follows:
* The PP-19 is now chambered in 9x18mm Makarov cartridges, and it already has the correct magazine capacity of 64 rounds
* CE and CE:FT do not support mixing of different calibers and magazine sizes, so I cannot add a 53-round 9x19mm variant
* The B&T MP9 is now chambered in 9x19mm Parabellum
