### ISSUE TITLE
Mortars not working if ammo system is disabled

### ISSUE THREAD

**Issue by MarcoE12388** [AthenaSulisMinerva/CombatExtendedFastTrack#72]
when playing without ammunition often and willingly mortars do not fire, especially sieges, they are only people who camp

~~quando si gioca senza munizioni spesso e volentieri i mortai non sparano, soprattutto gli assedi, sono solo delle persone che si accampano~~

~~scusate sono svizzero ma parlo solo l'italiano bene~~

~~sorry I'm Swiss but I only speak Italian well~~

**Comment by AthenaSulisMinerva** [comment]
This is a problem with the original CE mold, and has already been reported in  NoImageAvailable/CombatExtended/issues/704

Also, the CE:FT is composed of English speakers, so please only post in English. We can't rely on inaccurate Google Translations.
