### ISSUE TITLE
 create the "run and reload gun" patch for the "run and gun"

### ISSUE THREAD

**Issue by MarcoE12388** [AthenaSulisMinerva/CombatExtendedFastTrack#73]
~~mi spiace ma parlo italiano e i avvalgo di google traduttore~~

~~I'm sorry but I speak Italian and I use google translator~~

**Comment by AthenaSulisMinerva** [comment]
CE (and CE:FT) are already compatible with RunAndGun, and none of these mods have a "run and reload" feature of any kind.

Again, please only submit issues here in English. The CE:FT are all English speakers.

**Comment by MarcoE12388** [comment]
thank you very much, from now on I will write only in English but forgive me for any grammatical errors
