### ISSUE TITLE
I think traders have many HE, Incendiary, EMP shells.

### ISSUE THREAD

**Issue by Redonsku** [AthenaSulisMinerva/CombatExtendedFastTrack#80]
https://imgur.com/a/76nsdst

When exotic traders come, they have number of HE(red line) '274'. I think it's a lot of goods.
In vanilla case,  traders bring HE, incendiary, EMP shells number of roughly 80.

Could you set these amount like as vanilla?

**Comment by AthenaSulisMinerva** [comment]
Is this problem unique to CE:FT, or can you also reproduce it in the original CE mod?

**Comment by Redonsku** [comment]
> Is this problem unique to CE:FT, or can you also reproduce it in the original CE mod?

I did test about that, Original CE also has this issue. An exotic trader caravan bring 242 extinguisher shells.

**Comment by AthenaSulisMinerva** [comment]
In that case, you should raise this issue in the original CE repo, as CE:FT simply builds on the original CE by adding additional ammo and weapons patches. We don't fix core CE bugs.
