### ISSUE TITLE
Selectable Turret Target mod

### ISSUE THREAD

**Issue by wesley309** [AthenaSulisMinerva/CombatExtendedFastTrack#81]
i remember this mod seems can use at old ce version(or not ): 
https://steamcommunity.com/sharedfiles/filedetails/?id=869110833&searchtext=turret

![image](https://user-images.githubusercontent.com/51426545/66073574-dc406a00-e589-11e9-9d28-6e6385ca6a0d.png)

![image](https://user-images.githubusercontent.com/51426545/66073587-e7939580-e589-11e9-9c92-1ed86642a209.png)

really think that sometimes turret cant do well shot at correct target
(sorry for bad english, it's not my native language)

**Comment by AthenaSulisMinerva** [comment]
Are you experiencing this issue only in CE:FT v1.0.1.5-FT-004, or does it occur also with the original CE v1.0.1.5?

**Comment by wesley309** [comment]
I test it found its seem like  occur both ce mod.
![image](https://user-images.githubusercontent.com/51426545/66250865-1a50b000-e77b-11e9-923f-9ad56cb98126.png)

**Comment by AthenaSulisMinerva** [comment]
Since this issue also happens with the original CE, then it is the responsibility of the author of Selectable Turret Target to make his/her mod compatible with both CE and CE:FT.

In other words, not our problem.

**Comment by wesley309** [comment]
thx for the reply and check for the mod
