### ISSUE TITLE
Support for newest version of Genetic Rim and its patches like Spidercamp Dog Pack - Genetic Rim Patch, GeneticRim Cosmic Horrors Patch and etc

### ISSUE THREAD

**Issue by Hellcommander** [AthenaSulisMinerva/CombatExtendedFastTrack#82]
any plans to add support for genetic rim stuff (old patch is missing recent changes to genetic rim and has issues with weapon content like explosives apparently)

**Comment by AthenaSulisMinerva** [comment]
Please split your request into separate issues.
