### ISSUE TITLE
Is there a way to automatically determine compatibility?

### ISSUE THREAD

**Issue by githubuser1256** [AthenaSulisMinerva/CombatExtendedFastTrack#83]
I use about 50 mods; many of which are very important. The most important is CEFT. I have been careful to pick mods that are either strictly compatible with CEFT or that I don't _think_ have any incompatibilities. 

That said, despite my care, I believe there are mods causing conflicts with CEFT (or between two other mods) in my list. Strange things happen in-game.

Is there a reasonably easy way to see which mods are touching other mods so I don't have to request 30 mods be checked by you for compatibility?

**Comment by AthenaSulisMinerva** [comment]
Quite simply:

* The README contains a list of mods whose compatibility patches are already bundled in CE:FT, and you can be reasonably confident that those mods won't have compatibility issues.

* Any mod that is not listed in the README should be used with extreme caution.

**Comment by githubuser1256** [comment]
I just found and ran [[TOOL] RimWorld Conflict Checker [Updated 11/29/18]](https://ludeon.com/forums/index.php?topic=25305.0) which has given me some useful information, but lists no conflicts with CEFT whatsoever and 110 other mods. 

What is your general process to find conflicts? In order for you to find a conflict/compatibility, do you normally have to investigate the DLLs as well (as opposed to just the definitions?)

**Comment by Taranchuk** [comment]
As I usually do. If there is a mod that is not in the list of compatible mods in CE:FT description and it contains races, animals, weapons and armor, then I look for the word CombatExtended in the mod files. If there is no such word, then the patch was not made and the mod is not compatible with CE.

**Comment by AthenaSulisMinerva** [comment]
As this question has been answered sufficiently, I'm wrapping up this discussion.
