### ISSUE TITLE
Alpha Animals mod

### ISSUE THREAD

**Issue by Cooljoose** [AthenaSulisMinerva/CombatExtendedFastTrack#87]
Any chance for an Alpha Animals FT patch? Apparently there's already a standard CE patch, but it seems to be pretty outdated and reporting errors. Thanks!

Base mod: https://steamcommunity.com/sharedfiles/filedetails/?id=1541721856
Old patch: https://steamcommunity.com/sharedfiles/filedetails/?id=1594649493

**Comment by AthenaSulisMinerva** [comment]
We'll rewrite the patch ourselves as required.

**Comment by AthenaSulisMinerva** [comment]
Addressed in #146 and released in 1.0.1.8-FT-009.
