### ISSUE TITLE
Rimmu-Nation: IWI Negev LMG & Type 97 Bullpup AR

### ISSUE THREAD

**Issue by ChickenPluckers** [AthenaSulisMinerva/CombatExtendedFastTrack#88]
Hello all, forgot to mention this in the patch notes and was reported to not work with CE FT.

*wink* *wink* I heard Rimmu-Nation was a favourite of Athena and Sumghai (favourite source of headache) 

Defname:
**RNGun_NegevLMG**

From Rimmu-Nation .xml file:
RangedIndustrial_LMG.xml

Cheers all 

EDIT:
Also got complaints about this:
**RNGun_Type97AR**

See ya later, fair one, sorry innit

**Comment by sumghai** [comment]
Righto, I'd better get crackin'.

**Comment by sumghai** [comment]
Ah, I see what happened with the IWI Negev - it was patched for Elite Crew, but wasn't also included in RN Weapons patches. Easy peasy.

As for the Type 97 / QBZ-95, we haven't patched that yet. I'll get on that right away.

**Comment by sumghai** [comment]
As per the item description in RN Weapons, the Type 97 / QBZ-95 has been patched to use 5.56x45mm NATO cartridges rather than the usual Chinese 5.8x42mm DBP10.

This is good to go for the next update.
