### ISSUE TITLE
Incompatible Mods error

### ISSUE THREAD

**Issue by TheEventHorizon** [AthenaSulisMinerva/CombatExtendedFastTrack#9]
Whenever the mod is enabled the incompatible mod error is thrown. I have a screen shot and my Rimworld log attached. I hope this helps.

[https://www.dropbox.com/sh/bu9d7n5c29iqnoc/AAC1zOjo811Dlt1Jab09beuea?dl=0](url)

**Comment by AthenaSulisMinerva** [comment]
This is a known issue.

@sumghai and I invited a couple of people to submit their mod patches, but they weren't formatted correctly, so they were causing the errors you're seeing.

@sumghai is currently fixing those patches, but in the meantime, try rolling back to this version:

https://github.com/AthenaSulisMinerva/CombatExtendedFastTrack/archive/056f4564a6e65c37274d852d7ce6c92af4f6d76e.zip

**Comment by sumghai** [comment]
@TheEventHorizon @AthenaSulisMinerva Yup, I'm working on it.

Specifically, it's the hardcoded Ammo def folder from @Kik0hi Kik0hi's Forsakens patch is causing the issue. He said it's fine if I made the Forksakens use standard CE arrows instead.

I'll see what I can do tonight, although fixing the Rimworld of Magic patches is taking far longer than I expected, because of how many new gameplay changes it implements.

**Comment by sumghai** [comment]
@TheEventHorizon - Can you try the latest version of the repo now?

I've not only fixed all the "incompatible mods" errors, but also rolled in all the new content from the original upstream CE repo.

**Comment by TheEventHorizon** [comment]
@sumghai Absolutely ridiculous speed and quality! You and the whole team should be incredibly proud of the work you've done. Almost all errors are completely gone. The only error related to patches that've been able to find is that the Elite crew mod by Plucker when enabled with rimmu-nation weapons generates errors: Config error in RNThrown_C4CSGO: has stackLimit > 1 but also has drawGUIOverlay = false. and that the molotov cocktail has an incorrect forcedmissed setting.

**Comment by sumghai** [comment]
@TheEventHorizon - Good to hear that the worst of the bugs are gone now.

As for the Elite Crew and RN-Weapons explosives incompatibility issue, let me investigate that further. I swear I previously fixed that a while back...

(I guess that's the thing when you're patching a family of mods that share the same defs. Chicken Plucker should probably have made his mods more modular.)

**Comment by sumghai** [comment]
@TheEventHorizon - Okay, try the latest version of this repo now, with RN Weapons and Elite Crew running.

> **Long-winded explanation**
>
> The CE patches for RN mods generally remove all RN grenades, in favor of CE's existing grenades and textures. The sole exception is the RN CSGO C4 charge, which gets fully patched.
> 
> Because Elite Crew shares a number of defs with RN Weapons, I wrote some of the patches to run a conditional check to see whether RN Weapons is also active:
> * If yes, it lets the CE patch for RN weapons patch all the grenades
> * If no, it applies an Elite Crew-specific version of the CE patch
>
> My mistake was that I essentially put one of the checks in the wrong place, meaning that (at the time) it would actually fail to remove the RN grenades if both RN Weapons and Elite Crew were running. Splitting both sets of PatchOps up into separate files with separate conditional checks solved this issue.

**Comment by AthenaSulisMinerva** [comment]
Looks good on my end.

**Comment by AthenaSulisMinerva** [comment]
@TheEventHorizon, can you confirm that @sumghai's fix works for you?

I'd like to close this issue so that we can official release this mod.

**Comment by sumghai** [comment]
My bad, guys! Turns out there was one more patch I forgot to upload.

Try now, @TheEventHorizon.

**Comment by TheEventHorizon** [comment]
> My bad, guys! Turns out there was one more patch I forgot to upload.
> 
> Try now, @TheEventHorizon.

Working fine now! Thank you so much! 

Would it be possible to add support for Call of Cthulhu Cults mod? The current patch does not work. Hopefully it wouldn't be too hard.

**Comment by AthenaSulisMinerva** [comment]
@TheEventHorizon, I suggest starting a new, separate issue for each mod you want compatibility patches for.

I'll get @sumghai to look into that mod next time. For now, I think we're ready to do an official release.
