### ISSUE TITLE
Defensive Machine Gun Turret Pack - incorrect or unlimited turret ranges

### ISSUE THREAD

**Issue by Kubomius** [AthenaSulisMinerva/CombatExtendedFastTrack#90]
There's a unlimited range bug.

**Comment by AthenaSulisMinerva** [comment]
@sumghai - let's push this back for a later update, since we're pretty behind schedule already.

**Comment by sumghai** [comment]
Related to #89 - with the root cause and solution:

> Basically, every turret has the following values:
> * `range` - the actual range the turret gun will fire in
> * `specialDisplayRadius` - a circle of a given radius drawn with the building at its center; as the name implies, it is for display purposes only
> 
> What has happened is that:
> * Turret gun `range` values are higher in CE than in vanilla; this is because we calculate and re-balance stats based on real-world data 
> * However, we basically forgot to also update the `specialDisplayRadius` value
> 
> So basically, the turrets in CE **_do not_**, in fact, have infinite range - rather, it shows the old `specialDisplayRadius` value while it can now fire at the new (higher) `range` value. I can simply modify the patch so that the `specialDisplayRadius` will show the same value as the actual turret gun `range`.

**Comment by sumghai** [comment]
> Another thing that I found:
> 
> CE will hard cap the display radius to less than 90 cells (≈1060 meters in real life), and anything above that simply won't get drawn.
> 
> Since CE generally specifies typical turret ranges of 800m (75 cells), this means I will actually have to nerf the range of some of these turrets, just so that I can draw the display radii.

**Comment by sumghai** [comment]
This has now been fixed, and will be rolled in with the next update.
