### ISSUE TITLE
VGP Garden Fabrics

### ISSUE THREAD

**Issue by Caradog** [AthenaSulisMinerva/CombatExtendedFastTrack#91]
Any chance of patching this mod into CE:FT? https://steamcommunity.com/sharedfiles/filedetails/?id=1185269798

The materials added seem to be unbalanced - Linen cloth in particular is giving bigger sharp bonuses than hyperweave

Total list of materials I've found added by the mod include hemp cloth, linen cloth and blended wool

**Comment by AthenaSulisMinerva** [comment]
I'm not familiar with patching materials/stuffables for balance.

@sumghai? @Freedom187?

**Comment by sumghai** [comment]
Yeah, I'm not well-versed in patching materials either.

**Comment by Caradog** [comment]
Sorry - forgot all about this being open, the mod in question was patched on its end for CE compatibility, seems to work as intended now.
