### ISSUE TITLE
Cant Craft RPG's

### ISSUE THREAD

**Issue by Zombielorf** [AthenaSulisMinerva/CombatExtendedFastTrack#93]
I have all the required research done and all the different crafting benches, but none of them can craft the RPG.

**Comment by sumghai** [comment]
By default, CE and CE:FT will only allow crafting of RPG-7 ammo if you actually have a weapons mod that comes with a RPG-7 launcher (In fact, this is true for all CE ammo).

What other weapons mods are you running?

**Comment by Zombielorf** [comment]
none )_)

**Comment by sumghai** [comment]
In which case, you need to choose a mod that actually comes with a RPG-7 launcher, and only then will CE:FT allow you to craft RPG-7 ammo. 

Any one of the following will do:

* [Rimmu-Nation Weapons](https://steamcommunity.com/sharedfiles/filedetails/?id=1608498683)
* [Rimfire](https://ludeon.com/forums/index.php?topic=9536.0)

* [CE Guns](https://github.com/NoImageAvailable/CombatExtendedGuns) - designed for the original version of CE, but also works in CE:FT
