### ISSUE TITLE
Optimization: CE Ammo

### ISSUE THREAD

**Issue by HappyHead** [AthenaSulisMinerva/CombatExtendedFastTrack#94]
Owlchemist has an optimization mod which removes the definitions of any CE ammo not in use.
Internal integration plz?
https://steamcommunity.com/sharedfiles/filedetails/?id=1721900020&searchtext=ce+ammo

**Comment by sumghai** [comment]
I'm rather iffy about this optimization patch, to be honest.

The author, Owlchemist, notes that:

> Do note that if you use a large number of weapon mod packs that take advantage of all that extra ammo variety in CE, this mod may not serve much purpose.

> This optimization method, as it currently stands, will not work with gun mods that introduce mixed ammo sets. The patch relies on a 1:1 between ammo and the sets they belong to, as is often the case. The patch will check if any guns are using a set, and if not, delete the ammo defs belonging to it. But if that ammo belongs to another, mixed set that is being used... well, that's how you get red text errors!

I feel that this runs counter to CE:FT's vision of concurrently supporting as many third-party weapons mods as possible. 

Thoughts, @AthenaSulisMinerva and @Freedom187?

**Comment by AthenaSulisMinerva** [comment]
@sumghai pretty much hit the nail on the head, so I'm against this as well.

**Comment by sumghai** [comment]
@Freedom187 / RaptorX has been having trouble logging on to the web browser version of GitHub, but he concurs with our sentiments:

![convo with RaptorX aka Freedom187](https://user-images.githubusercontent.com/4993380/67153836-20ba5c80-f323-11e9-9a49-053bc47f0f9e.png)

**Comment by AthenaSulisMinerva** [comment]
Then it's decided - CE:FT won't integrate Optimization: CE Ammo.
