### ISSUE TITLE
colonist don't get ammo

### ISSUE THREAD

**Issue by IsaacXHB** [AthenaSulisMinerva/CombatExtendedFastTrack#98]
I had already assigned the loadout that include ammo and weapon to them , the type of ammo is correct , 
i also tried to forced them to pickup the ammo .
BUT EVERY TIME !!!
they put those ammo back after they picked it up immediately...
I tried many times , they still put it back...
how can i solve it ?
[https://steamcommunity.com/app/294100/discussions/0/1609400247643227000/?tscn=1571752980](url)

this is my mod list : 
<li>ModCheck</li>

<li>MOD-E</li>

<li>Core</li>

<li>RIMMSLoadUp</li>

<li>RuntimeGC</li>

<li>Startup impact</li>

<li>HugsLib</li>

<li>JecsTools</li>

<li>Miscellaneous 'CORE'</li>

<li>Combat Extended</li>

<li>Go Explore!</li>

<li>Dynamic Diplomacy</li>

<li>Mercenaries For Me</li>

<li>Doors Expanded</li>

<li>[RF] Fishing [1.0]</li>

<li>PhiClient</li>

<li>RimQuest</li>

<li>RimCities</li>

<li>Map Reroll</li>

<li>Real Ruins</li>

<li>More Steel</li>

<li>More Components</li>

<li>Master of Cooking</li>

<li>Master of Crafting</li>

<li>MendAndRecycle</li>

<li>Repair Workbench</li>

<li>Realistic Rooms</li>

<li>ED-Embrasures</li>

<li>[CP] Red Horse Furniture (1.0)</li>

<li>Door Mat R1.0</li>

<li>More Furniture [1.0]</li>

<li>Chickens Efficient Light</li>

<li>Wall Light</li>

<li>[sd] advanced powergeneration</li>

<li>Turn It On and Off v1.3 [1.0]</li>

<li>Rimefeller</li>

<li>SF [v1.0] Priority Treatment</li>

<li>Less Arbitrary Surgery</li>

<li>Smart Medicine</li>

<li>QualitySurgeon</li>

<li>GouRIMet</li>

<li>[RF] Packed Lunches [1.0]</li>

<li>[XND] Survival Tools</li>

<li>Musical Instruments</li>

<li>[CP] Rimmu-Nation - Clothing (All Craftable!) (1.0)</li>

<li>[CP] British Military Kit (1.0)</li>

<li>Metro Armory 1.0.0</li>

<li>Won hair_men</li>

<li>Won hair_women </li>

<li>[Uru] Rim Seraph hair (1.0)</li>

<li>ameiro anime hairs for 1.0</li>

<li>Rimsenal - Rimhair</li>

<li>Roppoi hair 1.0</li>

<li>Xeva's Rimhair</li>

<li>Misc. Training</li>

<li>Mad Skills</li>

<li>[KV] More Trait Slots - 1.0</li>

<li>Skilled Stonecutting</li>

<li>Combat Training</li>

<li>DontBlockDoorMod[1.0]</li>

<li>Common Sense</li>

<li>Psychology</li>

<li>Less Rebuff</li>

<li>RunAndGun</li>

<li>Share The Load</li>

<li>Misc. Robots</li>

<li>Animal Variety Coats</li>

<li>Optimization - RAID</li>

<li>Misc. TurretBase, Objects</li>

<li>[SYR] Bullet Casings</li>

<li>Avoid Friendly Fire</li>

<li>Death Rattle</li>

<li>Frontline - Bunkers</li>

<li>Remote Tech</li>

<li>[CP] Rimmu-Nation - Weapons (1.0)</li>

<li>Let's Trade! [1.0]</li>

<li>[KV] Trading Spot - 1.0</li>

<li>Roads of the Rim</li>

<li>[CP] Get to the Chopper! - Aircraft mod [1.0]</li>

<li>[RH] Faction: Task Force 141 (1.0)</li>

<li>[RH] Faction: Umbra Company (1.0)</li>

<li>Faction Discovery</li>

<li>[RH] Faction: The Ghosts (1.0)</li>

<li>More Faction Interaction</li>

<li>Variable Population</li>

<li>More Trade Ships</li>

<li>Accurate Mortars Lite</li>

<li>EdB Prepare Carefully[</li>

<li>Combat Effects for Combat Extended</li>

<li>Misc. XPatches CE</li>

<li>Deconstruct Return Fix</li>

<li>Faction_Discovery_zh</li>

<li>Reasonable Components V1</li>

<li>RimQuest_zh</li>

<li>Stack XXL</li>

<li>Better ModMismatch Window</li>

<li>Mod Manager</li>

<li>RimSaves</li>

<li>Dubs Mint Minimap</li>

<li>Level Up!</li>

<li>Recipe icons</li>

<li>Color Coded Mood Bar</li>

<li>Allow Tool</li>

<li>Colony Manager</li>

<li>Progress Renderer</li>

<li>Area Unlocker</li>

<li>Better Pawn Control</li>

<li>Damage Indicators</li>

<li>Dubs Mint Menus</li>

<li>Incident Person Stat</li>

<li>Interaction Bubbles</li>

<li>Medical Tab</li>

<li>Numbers</li>

<li>QualityBuilder</li>

<li>RaiderInfo</li>

<li>Relations Tab</li>

<li>RimHUD</li>

<li>Quest Tab</li>

<li>Static Quality Plus 1.2</li>

<li>ResearchPal</li>

<li>Verge of Galaxy (Music Mod) 1.0.0</li>

<li>P-Music</li>

<li>Tangerine Music Labs - Ambient Jams</li>

**Comment by AthenaSulisMinerva** [comment]
Does this happen with CE as well, or just CE:FT?

Start a new savegame with only Core and CE:FT, and see if you can still reproduce the problem.

If not, then add and test each of your other mods one at a time, to see when the problem occurs.

**Comment by IsaacXHB** [comment]
> Does this happen with CE as well, or just CE:FT?
> 
> Start a new savegame with only Core and CE:FT, and see if you can still reproduce the problem.
> 
> If not, then add and test each of your other mods one at a time, to see when the problem occurs.

ok , i will try this tough work... 
I will reply when i finish

**Comment by IsaacXHB** [comment]
> Does this happen with CE as well, or just CE:FT?
> 
> Start a new savegame with only Core and CE:FT, and see if you can still reproduce the problem.
> 
> If not, then add and test each of your other mods one at a time, to see when the problem occurs.

ok , i just had a test with only CEFT
My colonist only can pickup the amount or more than that i set to the loadout , 
but i tested couple of times , it become normal , colonist won't drop ammo no matter how many i force him to pick up . But it seems colonist won't pick up ammo by himself although i had already set the loadout to him..
I just don't know why...

**Comment by IsaacXHB** [comment]
ok , i find out the problem...
i'm so damn stupid..
the ammo in loadout is number of bullet
i though it was numbers of clip...
the colonist will drop all the ammo if the numbers of they pick up ...
nothing running wrong i think , i just Get it wrong...XDD
thanks
